### ISSUE TITLE
LDAP: Cannot use userAccountControl attribute in the search filter

### ISSUE THREAD

**Issue by misterunknown** [privacyidea/privacyidea#1026]
# What did you try to do?
Establish a ldap search filter, containing the userAccountControl attribute.

# What outcome did you expect?
We need to exclude disabled users from the LDAP server (MS Active Directory). The formal correct search filter is:
```
(!(userAccountControl:1.2.840.113556.1.4.803:=2))
```
But this didn't work.

# What do you think, how the system should have worked?
The system should use this filter. Instead an error occurs.

# What outcome did you experience?
An error occurs: `int() argument must be a string or a number, not 'NoneType'"`. This error can be either reproduced by trying to authenticate a user from the ldap server, or by testing the resolver in the configuration area.
This error occurs since we upgraded to 2.22. Our previous version (2.19.1) had no problems with that search filter.

# What did acutally happen?
The system can't authenticate against the ldap server.

# Configuration
* privacyIDEA Version: 2.22
* Installation method: virtualenv

## more details: 
* OS: Debian Jessie
* Webserver: Apache2.4
* Tokendatabase: MySQL

# Log file
```
[Thu Apr 19 13:05:59.038908 2018] [wsgi:error] [2018-04-19 13:05:59,038] ERROR in app: Exception on /auth [POST]
[Thu Apr 19 13:05:59.039106 2018] [wsgi:error] Traceback (most recent call last):
[Thu Apr 19 13:05:59.039237 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
[Thu Apr 19 13:05:59.039358 2018] [wsgi:error]     response = self.full_dispatch_request()
[Thu Apr 19 13:05:59.039532 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
[Thu Apr 19 13:05:59.039639 2018] [wsgi:error]     rv = self.handle_user_exception(e)
[Thu Apr 19 13:05:59.039745 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
[Thu Apr 19 13:05:59.039872 2018] [wsgi:error]     reraise(exc_type, exc_value, tb)
[Thu Apr 19 13:05:59.039976 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
[Thu Apr 19 13:05:59.040095 2018] [wsgi:error]     rv = self.dispatch_request()
[Thu Apr 19 13:05:59.040201 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
[Thu Apr 19 13:05:59.040323 2018] [wsgi:error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Apr 19 13:05:59.040429 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
[Thu Apr 19 13:05:59.040555 2018] [wsgi:error]     response = wrapped_function(*args, **kwds)
[Thu Apr 19 13:05:59.040659 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/api/auth.py", line 245, in get_auth_token
[Thu Apr 19 13:05:59.040796 2018] [wsgi:error]     user_obj = User(loginname, realm)
[Thu Apr 19 13:05:59.040900 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 154, in log_wrapper
[Thu Apr 19 13:05:59.041030 2018] [wsgi:error]     return func(*args, **kwds)
[Thu Apr 19 13:05:59.041160 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 98, in __init__
[Thu Apr 19 13:05:59.041267 2018] [wsgi:error]     self._get_user_from_userstore()
[Thu Apr 19 13:05:59.041387 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/usercache.py", line 63, in cache_wrapper
[Thu Apr 19 13:05:59.041494 2018] [wsgi:error]     return wrapped_function(*args, **kwds)
[Thu Apr 19 13:05:59.041615 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 106, in _get_user_from_userstore
[Thu Apr 19 13:05:59.041722 2018] [wsgi:error]     self._get_resolvers()
[Thu Apr 19 13:05:59.041845 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 207, in _get_resolvers
[Thu Apr 19 13:05:59.041953 2018] [wsgi:error]     if self._locate_user_in_resolver(resolvername):
[Thu Apr 19 13:05:59.042075 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/user.py", line 227, in _locate_user_in_resolver
[Thu Apr 19 13:05:59.042183 2018] [wsgi:error]     uid = y.getUserId(self.login)
[Thu Apr 19 13:05:59.042305 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 208, in cache_wrapper
[Thu Apr 19 13:05:59.042421 2018] [wsgi:error]     f_result = func(self, *args, **kwds)
[Thu Apr 19 13:05:59.042542 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 551, in getUserId
[Thu Apr 19 13:05:59.042648 2018] [wsgi:error]     attributes=attributes)
[Thu Apr 19 13:05:59.042773 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/ldap3/core/connection.py", line 741, in search
[Thu Apr 19 13:05:59.042878 2018] [wsgi:error]     request = search_operation(search_base, search_filter, search_scope, dereference_aliases, attributes, size_limit, time_limit, types_only, self.auto_escape, self.server.schema if self.server else None)
[Thu Apr 19 13:05:59.043008 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/ldap3/operation/search.py", line 358, in search_operation
[Thu Apr 19 13:05:59.043113 2018] [wsgi:error]     request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape).elements[0])  # parse the searchFilter string and compile it starting from the root node
[Thu Apr 19 13:05:59.043244 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/ldap3/operation/search.py", line 221, in compile_filter
[Thu Apr 19 13:05:59.043361 2018] [wsgi:error]     boolean_filter[pos] = compile_filter(element)
[Thu Apr 19 13:05:59.043493 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/ldap3/operation/search.py", line 233, in compile_filter
[Thu Apr 19 13:05:59.043615 2018] [wsgi:error]     boolean_filter['innerNotFilter'] = compile_filter(filter_node.elements[0])
[Thu Apr 19 13:05:59.043720 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/ldap3/operation/search.py", line 258, in compile_filter
[Thu Apr 19 13:05:59.043827 2018] [wsgi:error]     matching_filter['dnAttributes'] = DnAttributes(filter_node.assertion['dnAttributes'])
[Thu Apr 19 13:05:59.043954 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/pyasn1/type/univ.py", line 103, in __init__
[Thu Apr 19 13:05:59.044081 2018] [wsgi:error]     base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
[Thu Apr 19 13:05:59.044188 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/pyasn1/type/base.py", line 240, in __init__
[Thu Apr 19 13:05:59.044293 2018] [wsgi:error]     value = self.prettyIn(value)
[Thu Apr 19 13:05:59.044419 2018] [wsgi:error]   File "/opt/privacyidea/local/lib/python2.7/site-packages/pyasn1/type/univ.py", line 254, in prettyIn
[Thu Apr 19 13:05:59.044524 2018] [wsgi:error]     return int(value)
[Thu Apr 19 13:05:59.044649 2018] [wsgi:error] TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by fredreichbier** [comment]
Thanks for the bug report! You might have stumbled upon an ldap3 bug: https://github.com/cannatag/ldap3/issues/447
What version of ldap3 is installed in your virtualenv?

To resolve this, you can try upgrading ldap3 to 2.5 (not 2.4.1, this has a whole lot of other issues) and pyasn1 to 0.4.2.

**Comment by misterunknown** [comment]
Thanks for the quick reply. I changed the required version of ldap3 to 2.5 in `lib/python2.7/site-packages/privacyIDEA-2.22-py2.7.egg-info/requires.txt` and updated the package:
```
sed -i "/^ldap3/s/.*/ldap3>=2.5" lib/python2.7/site-packages/privacyIDEA-2.22-py2.7.egg-info/requires.txt
pip install -U ldap3
```
Now the filter works again. Do you plan to adjust this requirement in the repository?

**Comment by fredreichbier** [comment]
Glad to hear you got it working! Indeed, on current master, we require ldap3>=2.5 and pyasn1>=0.4.2 in setup.py (see #912).

I guess we can close this issue then :)
