### ISSUE TITLE
Migrate SCIMIdResolver

### ISSUE THREAD

**Issue by zenion** [privacyidea/privacyidea#109]
SCIMIdResolver calls for "from UserIdResolver import getResolverClass" which is a nonexistent function.

non-admin logins failing as so on base install with LDAP backend:

```
[2015-03-14 03:31:30,985][8013][140413549307840][WARNING][privacyidea.lib.config:496] unable to load resolver module : 'resolvers.SCIMIdResolver' (ImportError('cannot import name getResolverClass',))
[2015-03-14 03:31:31,025][8013][140413549307840][WARNING][privacyidea.lib.config:496] unable to load resolver module : 'resolvers.SCIMIdResolver' (ImportError('cannot import name getResolverClass',))
[2015-03-14 03:31:31,037][8013][140413549307840][WARNING][privacyidea.lib.config:496] unable to load resolver module : 'resolvers.SCIMIdResolver' (ImportError('cannot import name getResolverClass',))
[2015-03-14 03:31:31,059][8013][140413549307840][ERROR][privacyidea.app:1423] Exception on /auth [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/auth.py", line 178, in get_auth_token
    superuser_realms=superuser_realms)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 75, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 232, in login_mode
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/auth.py", line 119, in check_webui_user
    if user_obj.realm in superuser_realms:
TypeError: argument of type 'type' is not iterable
```

**Comment by cornelinux** [comment]
The ERROR is due to the config entry SUPERUSER_REALM in your pi.cfg.
It should be a list like

   SUPERUSER_REALM = ['superrealm']

I think it was fixed in the development tree.

**Comment by cornelinux** [comment]
The SCIM Resolver is not migrated, yet.

**Comment by zenion** [comment]
i see :) makes sense... keep up the amazing work. :)

**Comment by cornelinux** [comment]
Thanks for the compliment. (You are welcome to star this project ;-)

Did configuring the list work for you?

**Comment by zenion** [comment]
Absolutely. Was all too obvious once you mentioned it :-P... you've taken this so far so quickly since that initial fork. Of course I will star and support however I can.
