### ISSUE TITLE
Check: Rotate_audit log could get into a dead lock with ~800.000 entries

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1239]
When rotating with highwatermark and lowwatermark the rotation takes a long time and could run into a dead lock.

**Comment by fredreichbier** [comment]
Note: This also seems to happen if we use ``--age <...>``.

In case one has to delete a lot of rows, it generally seems to be a good idea to delete them in chunks (see [here](http://msutic.blogspot.com/2017/09/delete-large-amounts-of-data-on-galera.html), [here](https://stackoverflow.com/a/1318975)), because this will improve performance. I think this would also decrease the probability of deadlocks.

**Comment by fredreichbier** [comment]
As it turns out, it isn't that easy to delete audit rows in chunks in a way that is supported by our database backends.

MySQL has a ``DELETE FROM pidea_audit WHERE timestamp < X LIMIT 1000`` syntax, which we could simply execute in a loop until no entries are deleted anymore. However, this isn't supported by SQLAlchemy.

For SQLite, we could use ``DELETE FROM pidea_audit WHERE id IN (SELECT id FROM pidea_audit WHERE timestamp < X LIMIT 1000)``, but this isn't supported by MySQL (at least in my 5.7.23 server).

**Comment by cornelinux** [comment]
Did you reproduce that?
Would we not dead lock, if we would delete each audit row seperately? (Which of course would take a vast amount of time - just to narrow down things)

**Comment by fredreichbier** [comment]
I haven't reproduced any deadlocks yet, no :-/ I suspect they can only really be reproduced with a galera setup.

I'm not sure, but I think yes, having a lot of ``DELETE FROM pidea_audit WHERE id = X`` queries should reduce the risk of deadlocks. But it would probably be extremely slow if a lot of rows are deleted.

**Comment by fredreichbier** [comment]
I reproduced the deadlock with two privacyIDEA nodes and a 3-node galera cluster setup. Steps:

* Generate 800000 (fake) entries in the audit log
* Use ``siege -c4`` to generate a lot of authentication requests on both privacyIDEA nodes
* Run ``pi-manage rotate_audit --age 10`` on one node

Result:
```
Cleaning up with age: 10. mysql://galera:galera@192.168.0.241/pi
Deleting entries older than 2018-09-22 09:53:11.086138
Traceback (most recent call last):
  File "/opt/venv/bin/pi-manage", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/privacyidea/pi-manage", line 1164, in <module>
    manager.run()
  File "/opt/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/opt/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/opt/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/opt/privacyidea/pi-manage", line 676, in rotate_audit
    session.commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 471, in commit
    t[1].commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1643, in commit
    self._do_commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1674, in _do_commit
    self.connection._commit_impl()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1792, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') (Background on this error at: http://sqlalche.me/e/e3q8)
```

If we don't generate any load, the deadlock does not happen.
