### ISSUE TITLE
Galera: Restart transactions if a deadlock has occurred

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1268]
When using a galera cluster as a backend, deadlock errors may occur when committing a session. This especially happens when multiple nodes try to update the same database row, e.g. when using event counters:

```
[2018-10-01 17:55:57,766] ERROR in app: Exception on /validate/check [GET]
Traceback (most recent call last):
  File "/opt/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
...
  File "/opt/privacyidea/privacyidea/lib/counter.py", line 41, in increase
    counter.increase()
  File "/opt/privacyidea/privacyidea/models.py", line 2372, in increase
    self.save()
  File "/opt/privacyidea/privacyidea/models.py", line 2357, in save
    db.session.commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 471, in commit
    t[1].commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1643, in commit
    self._do_commit()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1674, in _do_commit
    self.connection._commit_impl()
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/opt/venv/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1792, in do_commit
    dbapi_connection.commit()
OperationalError: (_mysql_exceptions.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') (Background on this error at: http://sqlalche.me/e/e3q8)
```

It [seems to be a good idea](http://galeracluster.com/documentation-webpages/dealingwithmultimasterconflicts.html) to fix this at the application level and just restart transactions when a deadlock occurs.

We can actually do that pretty easily in many cases: We could just implement a decorator for model ``save`` methods which catches the above exception and just invokes the method again. For example, this should handle the event counter case above pretty nicely.

**Comment by fredreichbier** [comment]
I added such a decorator in [1268/retry-on-deadlock](https://github.com/privacyidea/privacyidea/tree/1268/retry-on-deadlock), and used it for ``EventCounter.save()`` and ``ClientApplication.save()``, because these are the only places I have seen deadlocks occur yet.

In my tests, this avoids the deadlocks at these locations pretty nicely:
```
# tail -f /var/log/privacyidea.log | grep -i deadlock
[2018-10-04 10:25:07,026][9211][140307634796416][INFO][privacyidea.models:107] Detected a deadlock while saving <ClientApplication [None][192.168.33.1:Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/4.0.4]>, retrying transaction
[2018-10-04 10:28:51,736][9224][140307634796416][INFO][privacyidea.models:107] Detected a deadlock while saving <ClientApplication [None][192.168.33.1:Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/4.0.4]>, retrying transaction
```
