### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by lidfgab** [privacyidea/privacyidea#1388]
# create database using utf8 support?
If i don't create database using UTF8, at lease the Chinese Chart in ldap configuration will change to ?????? 
If I create database by utf8 like this
"CREATE DATABASE privacyidea CHARACTER SET utf8 COLLATE utf8_general_ci;"
when pi-manage createdb , it will give me the follow logs
"
<SQLAlchemy engine=mysql://privacyidea:***@localhost/privacyidea?charset=utf8>
/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/default.py:508: Warning: InnoDB: ROW_FORMAT=DYNAMIC requires innodb_file_per_table.
  cursor.execute(statement, parameters)
/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/default.py:508: Warning: InnoDB: assuming ROW_FORMAT=COMPACT.
  cursor.execute(statement, parameters)
/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/default.py:508: Warning: Specified key was too long; max key length is 767 bytes
  cursor.execute(statement, parameters)
Traceback (most recent call last):
  File "/opt/privacyIDEA/bin/pi-manage", line 1168, in <module>
    manager.run()
  File "/opt/privacyIDEA/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/opt/privacyIDEA/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/opt/privacyIDEA/bin/pi-manage", line 493, in createdb
    db.create_all()
  File "/opt/privacyIDEA/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/opt/privacyIDEA/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/privacyIDEA/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1071, 'Specified key was too long; max key length is 767 bytes') [SQL: u'\nCREATE TABLE periodictasklastrun (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tperiodictask_id INTEGER, \n\tnode VARCHAR(256) NOT NULL, \n\ttimestamp DATETIME NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ptlrix_1 UNIQUE (periodictask_id, node), \n\tFOREIGN KEY(periodictask_id) REFERENCES periodictask (id)\n)ROW_FORMAT=DYNAMIC\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
"
I asked the same question for the previous version, it  was worked in that version, but it seems cannot create database in the latest version. 

* privacyIDEA Version:2.23.3

* Installation method:
  (from source, github, virtualenv, ubuntu packages...)
 from source

## more details: 

* OS: centos 7

* Webserver: Apache

* Tokendatabase: (like MySQL, PostgreSQL, ...)

# Log file

**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

**Comment by cornelinux** [comment]
This is a known mysql problem for certain mysql version.
> 1071, 'Specified key was too long; max key length is 767 bytes

You need to set the following in your mysql config:
~~~~ini
[mysqld]
innodb_large_prefix=on
innodb_file_format=Barracuda
~~~~

**Comment by lidfgab** [comment]
after upgrade mariadb to version 10.3.12 using MariaDB yum and create database using utf8
pi-manage createdb   
No handlers could be found for logger "privacyidea.lib.auditmodules.sqlaudit"
/opt/privacyIDEA/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
   
<SQLAlchemy engine=mysql://privacyidea:***@localhost/privacyidea?charset=utf8>

pi-manage.py admin add admin -e admin@localhost
-bash: pi-manage.py: command not found
(privacyIDEA) [root@svlvlwncc00003 privacyIDEA]# pi-manage admin add admin -e admin@localhost   
No handlers could be found for logger "privacyidea.lib.auditmodules.sqlaudit"
/opt/privacyIDEA/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
   
Password: 
Confirm: 
/opt/privacyIDEA/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:242: SAWarning: Unicode type received non-unicode bind param value '$pbkdf2-sha512$10023$ee.d...'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
Admin admin was registered successfully.

will this work fine for privacyidea?

**Comment by plettich** [comment]
These warnings are known and should not prevent privacyIDEA from working.
