### ISSUE TITLE
Migration tokenowners could fail with an open transaction

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1453]
When migrating it can happen that a transaction is left open.
~~~~
# ./pi-manage db upgrade

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
   
Running online
Can not create table 'tokenowner'. It probably already exists
(pymysql.err.InternalError) (1050, u"Table 'tokenowner' already exists") [SQL: u'\nCREATE TABLE tokenowner (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\ttoken_id INTEGER, \n\tresolver VARCHAR(120), \n\tuser_id VARCHAR(320), \n\trealm_id INTEGER, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(realm_id) REFERENCES realm (id), \n\tFOREIGN KEY(token_id) REFERENCES token (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/2j85)
Failed to migrate token assignment data!
(pymysql.err.InternalError) (1054, u"Unknown column 'token.user_id' in 'field list'") [SQL: u'SELECT token.id AS token_id, token.serial AS token_serial, token.resolver AS token_resolver, token.resolver_type AS token_resolver_type, token.user_id AS token_user_id \nFROM token \nWHERE token.user_id'] (Background on this error at: http://sqlalche.me/e/2j85)
Traceback (most recent call last):
  File "./pi-manage", line 1170, in <module>
    manager.run()
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "migrations/env.py", line 79, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/cornelius/src/privacyidea/venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 351, in run_migrations
    % step)
alembic.util.exc.CommandError: Migration "upgrade cb6d7b7bae63 -> 48ee74b8a7c8, Add tokenowner table and move tokenuser data to new table" has left an uncommitted transaction opened; transactional_ddl is False so Alembic is not committing transactions
~~~~

Looks like this can be avoided like this:

~~~~python
     except Exception as exx:
+        session.rollback()
         print("Failed to migrate token assignment data!")
         print (exx)
~~~~

**Comment by fredreichbier** [comment]
Fixed by #1454
