### ISSUE TITLE
Edit placeholder at Config>Users>sqlresolver>Driver

### ISSUE THREAD

**Issue by tamaro-skaljic** [privacyidea/privacyidea#1591]
The placeholder says "mysql" but should say "mysql+pymysql"
-Friedrich Weber, on 24th April 2019 at 03:18 pm

**Comment by fredreichbier** [comment]
Just for completeness: If we enter ``mysql`` as the driver, like suggested by the placeholder and test the connection, we get the following error:
```
 libmysqlclient.so.20: cannot open shared object file: No such file or directory
```

Traceback in the apache error log:
```
[Thu Apr 25 12:44:15.532687 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516] [2019-04-25 12:44:15,527] ERROR in app: Exception on /resolver/test [POST]
[Thu Apr 25 12:44:15.532708 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516] Traceback (most recent call last):
[Thu Apr 25 12:44:15.532710 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
[Thu Apr 25 12:44:15.532712 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     response = self.full_dispatch_request()
[Thu Apr 25 12:44:15.532714 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Thu Apr 25 12:44:15.532716 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     rv = self.handle_user_exception(e)
[Thu Apr 25 12:44:15.532717 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
[Thu Apr 25 12:44:15.532719 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     reraise(exc_type, exc_value, tb)
[Thu Apr 25 12:44:15.532721 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Thu Apr 25 12:44:15.532722 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     rv = self.dispatch_request()
[Thu Apr 25 12:44:15.532724 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
[Thu Apr 25 12:44:15.532726 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Apr 25 12:44:15.532727 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 154, in log_wrapper
[Thu Apr 25 12:44:15.532729 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     return func(*args, **kwds)
[Thu Apr 25 12:44:15.532730 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
[Thu Apr 25 12:44:15.532736 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     return wrapped_function(*args, **kwds)
[Thu Apr 25 12:44:15.532737 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/api/resolver.py", line 186, in test_resolver
[Thu Apr 25 12:44:15.532739 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     success, desc = pretestresolver(rtype, param)
[Thu Apr 25 12:44:15.532740 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/log.py", line 154, in log_wrapper
[Thu Apr 25 12:44:15.532742 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     return func(*args, **kwds)
[Thu Apr 25 12:44:15.532743 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/resolver.py", line 397, in pretestresolver
[Thu Apr 25 12:44:15.532745 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     (success, desc) = r_obj_class.testconnection(params)
[Thu Apr 25 12:44:15.532746 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/privacyidea/lib/resolvers/SQLIdResolver.py", line 652, in testconnection
[Thu Apr 25 12:44:15.532748 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     engine = create_engine(connect_string)
[Thu Apr 25 12:44:15.532749 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
[Thu Apr 25 12:44:15.532750 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     return strategy.create(*args, **kwargs)
[Thu Apr 25 12:44:15.532752 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
[Thu Apr 25 12:44:15.532753 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     dbapi = dialect_cls.dbapi(**dbapi_args)
[Thu Apr 25 12:44:15.532754 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 102, in dbapi
[Thu Apr 25 12:44:15.532756 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     return __import__('MySQLdb')
[Thu Apr 25 12:44:15.532757 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]   File "/opt/privacyidea/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
[Thu Apr 25 12:44:15.532759 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516]     import _mysql
[Thu Apr 25 12:44:15.532760 2019] [wsgi:error] [pid 13397:tid 139732631283456] [remote 192.168.33.1:516] ImportError: libmysqlclient.so.20: cannot open shared object file: No such file or directory
```

The error disappears if we install ``libmysqlclient20``. Maybe we should rather add this package as a requirement for the Ubuntu packages.
