### ISSUE TITLE
generating encryption key fails with privacyidea 3.0

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1594]
# What did you try to do?
generating encryption key

pi-manage create_enckey

Please provide your top level intent!
Please provide steps to reproduce!

# What outcome did you expect?
generating encryption key

What do you think, how the system should have worked?

# What outcome did you experience?

What did acutally happen?

privacyidea_web_1  | Traceback (most recent call last):
privacyidea_web_1  |   File "/PRIVACYIDEA/python/bin/pi-manage", line 1231, in <module>
privacyidea_web_1  |     manager.run()
privacyidea_web_1  |   File "/PRIVACYIDEA/python/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
privacyidea_web_1  |     result = self.handle(argv[0], argv[1:])
privacyidea_web_1  |   File "/PRIVACYIDEA/python/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
privacyidea_web_1  |     res = handle(*args, **config)
privacyidea_web_1  |   File "/PRIVACYIDEA/python/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
privacyidea_web_1  |     return self.run(*args, **kwargs)
privacyidea_web_1  |   File "/PRIVACYIDEA/python/bin/pi-manage", line 446, in create_enckey
privacyidea_web_1  |     f.write(DefaultSecurityModule.random(96))
privacyidea_web_1  | TypeError: <flask_script.commands.Command object at 0x7f0ac4667940>: write() argument must be str, not bytes
privacyidea_privacyidea_web_1 exited with code 1

# Configuration

* python Version: python 3.6.5

* privacyIDEA Version: privacyidea 3.0

* Installation method: virtualenv
  (from source, github, virtualenv, ubuntu packages...)

## more details: 

* OS: alpine 3.7

* Webserver: gunicorn

* Tokendatabase: Mariadb

# Log file

**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

**Comment by p53** [comment]
https://stackoverflow.com/questions/5512811/builtins-typeerror-must-be-str-not-bytes

**Comment by p53** [comment]
#1595

**Comment by cornelinux** [comment]
Obviously we need to do an open(... "wb") here:

https://github.com/privacyidea/privacyidea/blob/master/pi-manage#L458
