### ISSUE TITLE
Configuring pre-eventhandler with empty condition breaks authentication

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1658]
When adding a pre-eventhandler and activating a condition **without** specifying a value, we'll get an entry in the eventhandlercondition table without a value as well.
If this eventhandler is triggered, it fails with a `IndexError: string index out of range`.
In case of a **post**-eventhandler, the empty condition value is silently ignored and no entry in the eventhandlercondition table is created.
I guess, this is an UI issue, but we should check the the table entries for consistency anyway before using the values (See #1596).

**Comment by cornelinux** [comment]
This happens if e.g. the client IP condition is checked but there is a *blank* in the condition.
If the condition is really empty (none or 0 string), then the condition will not be saved.

**Comment by fredreichbier** [comment]
For me, the error also happens with ``count_auth``. The condition looks like this:
```
sqlite> SELECT * FROM eventhandlercondition;
1|1|count_auth||equal
```

And the traceback looks like this:
```
127.0.0.1 - - [14/Jun/2019 10:33:55] "POST /validate/check HTTP/1.1" 500 -
[2019-06-14 10:33:56,941] ERROR in app: Exception on /validate/check [POST]
Traceback (most recent call last):
  File "/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fred/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/lib/decorators.py", line 96, in check_user_or_serial_in_request_wrapper
    f_result = func(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/lib/subscriptions.py", line 333, in check_subscription_wrapper
    f_result = func(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/privacyidea/privacyidea/privacyidea/lib/event.py", line 75, in event_wrapper
    if event_handler.check_condition(options=options):
  File "/home/fred/privacyidea/privacyidea/privacyidea/lib/eventhandler/base.py", line 496, in check_condition
    if not compare_condition(cond, count):
  File "/home/fred/privacyidea/privacyidea/privacyidea/lib/utils.py", line 752, in compare_condition
    if condition[0] in "=" + string.digits:
IndexError: string index out of range
```

**Comment by cornelinux** [comment]
I added a new commit e64c9d95 to the PR. Please take a look

**Comment by cornelinux** [comment]
Changed the topic to understand better, how authentication breaks... when we sum up the changelog.
