### ISSUE TITLE
500 when trying to enroll token on Postgres: operator does not exist: character varying = integer

### ISSUE THREAD

**Issue by tyteen4a03** [privacyidea/privacyidea#1885]
### Top-level intent
Adding a new Token will cuase the server to throw an exception `operator does not exist: character varying = integer`.

### Steps to reproduce

1. Install PrivacyIDEA with Postgres.
2. Attempt to add a new token.

### Expected outcome

The request should not fail.

### Actual outcome

The request fails with a 500, however the token entry is added.

### Configuration

* **privacyIDEA version**: 3.1.1
* **Installation method**: (from Ubuntu packages, github, PyPI, ...) PyPI
* **Python version**: 3.7
* **Operating system**: macOS Catalina
* **Webserver**: N/A
* **Token database**: (MySQL, PostgreSQL, ...) PostgreSQL

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

```
[2019-10-12 00:25:07,425][38366][4393209152][ERROR][privacyidea.app:1891] Exception on /token/init [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: operator does not exist: character varying = integer
LINE 3: ...RE tokenowner.token_id = 8 AND tokenowner.user_id = 1 AND to...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/api/lib/prepolicy.py", line 129, in policy_wrapper
    return wrapped_function(*args, **kwds)
  [Previous line repeated 15 more times]
  File "/usr/local/lib/python3.7/site-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/lib/subscriptions.py", line 333, in check_subscription_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/lib/event.py", line 99, in event_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/lib/log.py", line 193, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/api/token.py", line 257, in init
    tokenrealms=tokenrealms)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/lib/log.py", line 193, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/lib/token.py", line 1032, in init_token
    tokenobject.add_user(user)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/lib/decorators.py", line 44, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/privacyidea/lib/tokenclass.py", line 204, in add_user
    realmname=user.realm).save()
  File "/usr/local/lib/python3.7/site-packages/privacyidea/models.py", line 1108, in save
    resolver=self.resolver).first()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3240, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: character varying = integer
LINE 3: ...RE tokenowner.token_id = 8 AND tokenowner.user_id = 1 AND to...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT tokenowner.id AS tokenowner_id, tokenowner.token_id AS tokenowner_token_id, tokenowner.resolver AS tokenowner_resolver, tokenowner.user_id AS tokenowner_user_id, tokenowner.realm_id AS tokenowner_realm_id, realm_1.id AS realm_1_id, realm_1.name AS realm_1_name, realm_1."default" AS realm_1_default, realm_1.option AS realm_1_option
FROM tokenowner LEFT OUTER JOIN realm AS realm_1 ON realm_1.id = tokenowner.realm_id
WHERE tokenowner.token_id = %(token_id_1)s AND tokenowner.user_id = %(user_id_1)s AND tokenowner.realm_id = %(realm_id_1)s AND tokenowner.resolver = %(resolver_1)s
 LIMIT %(param_1)s]
[parameters: {'token_id_1': 8, 'user_id_1': 1, 'realm_id_1': 1, 'resolver_1': 'TTPSWeb', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
[2019-10-12 00:25:07,438][38366][4393209152][DEBUG][privacyidea.lib.auditmodules.base:185] Entering log with arguments (<privacyidea.lib.auditmodules.sqlaudit.Audit object at 0x106d54910>, {'info': '500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.'}) and keywords {}
[2019-10-12 00:25:07,438][38366][4393209152][DEBUG][privacyidea.lib.auditmodules.base:197] Exiting log with result None
[2019-10-12 00:25:07,501][38366][4393209152][DEBUG][privacyidea.api.before_after:90] End handling of request '/token/init?'
```

**Comment by cornelinux** [comment]
I think this might be an issue on macos, which we officially do not support.
@plettich what do you think - postgres usually runs like a charm.

@tyteen4a03 Which postgres driver did you use in the SQL URI?

**Comment by tyteen4a03** [comment]
@cornelinux Should be connecting to my docker instance on alpine, but I can double-checked.

**Comment by plettich** [comment]
This should not happen anymore since we convert all user IDs to strings before working with them.
