### ISSUE TITLE
pi-manage restore does not work with Python 3

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1982]
### Top-level intent

Restore a backup with pi-manage

### Steps to reproduce

1. Install privacyIDEA 3.2.1 on Ubuntu
2. Run a backup with ``pi-manage backup create``
3. Run the restore with ``pi-manage backup restore <filename>``

### Expected outcome

Should be restored.

### Actual outcome

~~~~
Traceback (most recent call last):
  File "/usr/bin/pi-manage", line 1254, in <module>
    manager.run()
  File "/opt/privacyidea/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/opt/privacyidea/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/opt/privacyidea/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/bin/pi-manage", line 352, in restore
    for line in std_out.split(r"\n"):
TypeError: <flask_script.commands.Command object at 0x7f8b3c29bc18>: a bytes-like object is required, not 'str'
~~~~

### Configuration

* **privacyIDEA version**: 3.2.1
* **Installation method**: Ubuntu 18.04
* **Python version**: Python 3

It looks like we have some byte/string problems in the restore process with Python 3.
We probably need to unify the ``split`` and ``re.search`` calls.

**Comment by cornelinux** [comment]
@plettich: we could cherry pick this into 3.2 branch?
