### ISSUE TITLE
TypeError for LDAP password

### ISSUE THREAD

**Issue by c-momi** [privacyidea/privacyidea#2018]
### Top-level intent

Get users from LDAP resolver.

### Steps to reproduce

1. Create LDAP resolver with OpenLDAP and attach to a realm
2. Set the resolver's Attribute mapping to read the password
3. Go to /#/user/list

### Expected outcome

Users list should be displayed

### Actual outcome

Red banner with "Error 500" is displayed.

I edited the code to print the obj that was triggering the exception. It's that password field in bytes type.
`{'surname': 'MySurname', 'email': 'user@example.com', 'username': 'user@example.com', 'password': b'{SSHA512}V2Q1IzsX2pwAqUJFo/dNBOKL0+RzG9Jxo1rX/vhOMGKkVrK+7Fc4PlqBQYw9usfOtxc4ceLBgv1SCIo28zIT93Wpn+anM7EB', 'userid': '5419851c-d893-1039-8c4a-a9115c24acfb', 'resolver': 'ldap1', 'editable': False}`

### Configuration

* **privacyIDEA version**: 3.2.2
* **Installation method**: PyPI
* **Python version**: 3.6.9
* **Operating system**: Ubuntu 18
* **Webserver**: uwsgi 2.0.18 (from PyPI)
* **Token database**: sqlite

### Log file

```
Exception on /user/ [GET]
Traceback (most recent call last):
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 131, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 131, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/privacyidea/api/auth.py", line 374, in decorated_function
    return f(*args, **kwargs)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/privacyidea/lib/event.py", line 99, in event_wrapper
    f_result = func(*args, **kwds)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/privacyidea/api/user.py", line 112, in get_users
    return send_result(users)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/privacyidea/api/lib/utils.py", line 107, in send_result
    return jsonify(prepare_result(obj, rid, details))
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/user/privacyidea/env/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

```

**Comment by c-momi** [comment]
As a side note, the same configuration works (doesn't raise any exception) when using privacyidea with python2

**Comment by c-momi** [comment]
To solve this, just remove the “password“ field from attribute mapping in your ldap resolver configuration.

It doesn’t make much sense to retrieve the user password from ldap. Even policies with otppin=userstore don’t need that. I would say this issue is a wontfix. It took me some time to realize it so I felt like sharing.

**Comment by cornelinux** [comment]
Thanks for the comments, @c-momi 
You can easily use the buttons "Preset openldap" or "preset AD".
The LDAP requires no password mapping, since privacyIDEA does not "need to know" the password to verify it. It is done by issuing a bind request to LDAP.
