### ISSUE TITLE
UI: provide reasonable error messages on token import

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2073]
Hi,

I came across an "Internal Server Error" message when accessing the "Import Tokens" in the WebUI. The log file contains a ValueError exception since the directory /etc/privacyidea/gpg was not found.
https://gist.github.com/laclaro/4720ecf2a84b7eaa1a141acd0d428bc2

It concerns this line
https://github.com/privacyidea/privacyidea/blob/2dd920e90ab42ed35fc717e29cec9c1e4c6b797a/privacyidea/lib/importotp.py#L550

We should catch this case providing the user with more information.

How to resolve?
* Check if directory is there, if not, print error message
* If directory is there, check if keys are available, if not, print error message.

Best,

Henning

**Comment by cornelinux** [comment]
I don't think so. Actually this part to my knowledge is used by...
...noone.
So currently I see no need in adding more code here.

**Comment by laclaro** [comment]
Most users have a packaged installation of PI, I suspect. If the directory gets created by the package, no reason to take actions at the moment, agreed.

**Comment by cornelinux** [comment]
We could so a simple existance check, only to get this issue closed ;-)

like

~~~~python
import os
if os.path.isdir(self.gnupg_home):
    self.gpg = gnupg.GPG(gnupghome=self.gnupg_home) 
else:
   # bail out
~~~~

~~~~python
[2020-03-10 12:10:24,391][11480][140689530718016][ERROR][privacyidea.app:1891] Exception on /system/gpgkeys [GET]
Traceback (most recent call last):
  File "/home/henning/Dokumente/Dev/privacyidea-server/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/henning/Dokumente/Dev/privacyidea-server/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/henning/Dokumente/Dev/privacyidea-server/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/henning/Dokumente/Dev/privacyidea-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/henning/Dokumente/Dev/privacyidea-server/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/henning/Dokumente/Dev/privacyidea-server/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hom
e/henning/Dokumente/Dev/privacyidea-server/privacyidea/api/system.py", line 124, in get_gpg_keys
    GPG = GPGImport(current_app.config)
  File "/home/henning/Dokumente/Dev/privacyidea-server/privacyidea/lib/importotp.py", line 550, in __init__
    self.gpg = gnupg.GPG(gnupghome=self.gnupg_home)
  File "/home/henning/Dokumente/Dev/privacyidea-server/venv/lib/python3.6/site-packages/gnupg.py", line 818, in __init__
    raise ValueError('gnupghome should be a directory (it isn\'t): %s' % gnupghome)
ValueError: gnupghome should be a directory (it isn't): /etc/privacyidea/gpg
~~~~

**Comment by laclaro** [comment]
Now the message is not displayed anymore, but the user would assume that the feature would work.

Better would be to additionally disable the import button or to log to the warning to the WebUI instead.

**Comment by cornelinux** [comment]
Oh come on.
Now? What does this mean? Was anything changed?

**Comment by cornelinux** [comment]
The button must not be disabled (See my comment in the PR). Anything is fine this way.
If there is no GPG key displayed a user can not provide a public pgp key and thus not import encrypted files, because files can not be encrypted.
