### ISSUE TITLE
NameError: name 'unicode' is not defined 

### ISSUE THREAD

**Issue by brunocascio** [privacyidea/privacyidea#2086]
### Top-level intent

What did you try to achieve?

Create an HTTP resolver via the command line (http resolver via #2083 ) raises the exception.

### Steps to reproduce

1. `./pi-manage resolver create "http-resolver" httpresolver /tmp/http-params.py`

### Expected outcome

What do you think, how the system should have worked?

The resolver should be created successfully.

### Actual outcome

What did actually happen?

Raise the exception: "NameError: name 'unicode' is not defined"

### Configuration

* **privacyIDEA version**: master version
* **Installation method**: github
* **Python version**: 3.7
* **Operating system**: (docker python:3.7 version)
* **Webserver**: development server
* **Token database**: MSSQL

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

```
Traceback (most recent call last):
  File "./pi-manage", line 1261, in <module>
    manager.run()
  File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "./pi-manage", line 813, in create
    save_resolver(params)
  File "/home/pi/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/home/pi/privacyidea/lib/resolver.py", line 98, in save_resolver
    raise Exception("resolver type : {0!s} not in {1!s}".format(resolvertype, unicode(resolvertypes)))
NameError: name 'unicode' is not defined
```

**Comment by plettich** [comment]
Fixed with #2087
