### ISSUE TITLE
Installation form PyPI fails

### ISSUE THREAD

**Issue by markgraf** [privacyidea/privacyidea#2107]
### Top-level intent

I tried to install privacyidea from the Python Package index as detailed in https://privacyidea.readthedocs.io/en/latest/installation/pip.html#pip-install

The installation failed.

### Steps to reproduce

1. setup vm
2. follow install-instructions
3. fail

### Expected outcome

I would have expected the install to succeed.

### Actual outcome

```
root@myserver:/opt/privacyidea
$ pip install privacyidea
Downloading/unpacking privacyidea
  Downloading privacyIDEA-3.2.2.tar.gz (2.4MB): 2.4MB downloaded
  Running setup.py (path:/tmp/pip-build-TmWkLZ/privacyidea/setup.py) egg_info for package privacyidea
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    
    warning: no previously-included files matching '*' found under directory 'venv'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.git' found anywhere in distribution
Downloading/unpacking Flask>=0.10.1 (from privacyidea)
  Downloading Flask-1.1.1-py2.py3-none-any.whl (94kB): 94kB downloaded
Downloading/unpacking Flask-Migrate>=1.2.0 (from privacyidea)
  Downloading Flask_Migrate-2.5.3-py2.py3-none-any.whl
Downloading/unpacking Flask-SQLAlchemy>=2.0 (from privacyidea)
  Downloading Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl
Downloading/unpacking Flask-Script>=2.0.5 (from privacyidea)
  Downloading Flask-Script-2.0.6.tar.gz (43kB): 43kB downloaded
  Running setup.py (path:/tmp/pip-build-TmWkLZ/Flask-Script/setup.py) egg_info for package Flask-Script
    
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking Jinja2>=2.10.1 (from privacyidea)
  Downloading Jinja2-2.11.1-py2.py3-none-any.whl (126kB): 126kB downloaded
Downloading/unpacking Mako>=0.9.1 (from privacyidea)
  Downloading Mako-1.1.2-py2.py3-none-any.whl (75kB): 75kB downloaded
Downloading/unpacking PyMySQL>=0.6.6 (from privacyidea)
  Downloading PyMySQL-0.9.3-py2.py3-none-any.whl (47kB): 47kB downloaded
Downloading/unpacking Pillow>=6.2.1 (from privacyidea)
  Downloading Pillow-7.0.0.tar.gz (38.2MB): 38.2MB downloaded
  Running setup.py (path:/tmp/pip-build-TmWkLZ/Pillow/setup.py) egg_info for package Pillow
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-TmWkLZ/Pillow/setup.py", line 304
        yield from self.features
                 ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-TmWkLZ/Pillow/setup.py", line 304

    yield from self.features

             ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
```

### Configuration

* **privacyIDEA version**: 3.2.2
* **Installation method**: (from Ubuntu packages, github, PyPI, ...) PyPi
* **Python version**: 2.7
* **Operating system**: Debian Jessie
* **Webserver**: didn't get this far
* **Token database**: (MySQL, PostgreSQL, ...) didn't get this far

**Comment by markgraf** [comment]
This is likely an issue with Pillow, see https://github.com/python-pillow/Pillow/issues/4478
Didn't see that before, sorry...

**Comment by plettich** [comment]
Yes, this is a known Problem. pip always tries to install the latest greatest packages but more and more are incompatible with python 2.7
A good idea might be to switch to python 3.
