### ISSUE TITLE
Additional token list columns provided by "user_details" policy cannot be sorted

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2650]
Using the `user_details` policy, Error500 is thrown trying to sort or filter the UserID and User Store columns in the WebUI.

The exception trace is this:

```
[2021-03-02 16:19:27,439][18278][140425289365248][ERROR][privacyidea.app:1892] Exception on /token/ [GET]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/event.py", line 99, in event_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/token.py", line 421, in list_api
    tokeninfo=tokeninfo)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/token.py", line 501, in get_tokens_paginate
    sql_query = sql_query.order_by(sortby.asc())
AttributeError: 'NoneType' object has no attribute 'asc'
```

**Comment by cornelinux** [comment]
Can you please tell how to reproduce. Thx.

**Comment by laclaro** [comment]
Reproduce by setting a webui policy with action `user_details`, displaying the token list and trying to sort the additional columns resolver and userID.

After some investigation, this is just a UI bug. The UI displays the filter and sorting possibility for the new columns, but these are not informations in the token table. Therefore the lib function `get_tokens_paginate` gets called with "sortby=resolver", which is not found as a column (then `sortby` is None) and produces the above error.

This will be resolved by not allowing to sort by user id or resolver name in the token list.

**Comment by cornelinux** [comment]
Actually these have been columns in 2.X. In version 3 we moved to the tokenowner table, so it was not sortable anymore.
But it did not came up, since usually the columns are not displayed.
