### ISSUE TITLE
 Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")

### ISSUE THREAD

**Issue by FloMeyer** [privacyidea/privacyidea#2670]
### Top-level intent

What did you try to achieve?

### Steps to reproduce

1. using default objectGUID of Active Directory as UID type

### Expected outcome

What do you think, how the system should have worked?
normal

### Actual outcome

What did actually happen?

 Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")

But the objectGUID is not string..
![image](https://user-images.githubusercontent.com/2670188/111000733-e1126b80-8382-11eb-8949-0aa226bc0a9b.png)
![image](https://user-images.githubusercontent.com/2670188/111000758-ebcd0080-8382-11eb-9d17-1c646ea658d3.png)

If i set UID Type to DN, everything works, but i dont want to use DN as UID Type. ObjectGUID is fine.

### Configuration

* **privacyIDEA version**: 3.5.1
* **Installation method**: from Ubuntu packages
* **Python version**:  3.8
* **Operating system**: Ubuntu 20
* **Webserver**: apache2
* **Token database**: MySQL

### Log file

`

[2021-03-12 21:12:47,629][123262][140672039892736][ERROR][privacyidea.app:1891] Exception on /token/ [GET]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/auth.py", line 402, in decorated_function
    return f(*args, **kwargs)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/before_after.py", line 109, in before_user_request
    before_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/before_after.py", line 156, in before_request
    request.User = get_user_from_param(request.all_data)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/user.py", line 585, in get_user_from_param
    user_object = User(login=username, realm=realm,
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/user.py", line 101, in __init__
    self._get_user_from_userstore()
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/usercache.py", line 61, in cache_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/usercache.py", line 235, in user_init
    if self._locate_user_in_resolver(resolvername):
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/user.py", line 230, in _locate_user_in_resolver
    uid = y.getUserId(self.login)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 258, in cache_wrapper
    f_result = func(self, *args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 629, in getUserId
    userid = self._get_uid(entry, self.uidtype)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 420, in _get_uid
    uid = uid.strip("{").strip("}")
TypeError: a bytes-like object is required, not 'str'
[2021-03-12 21:12:47,854][123262][140672048285440][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")

`

**Comment by cornelinux** [comment]
Please provide the version of ``ldap3`` used and the version of you AD (server version).

**Comment by FloMeyer** [comment]
ldap3 is 2.8.1 and AD is Windows 2016.

**Comment by gavwellis** [comment]
Can you point me to where you are trying to achieve this in the code?

**Comment by FloMeyer** [comment]
Just install privacyIDEA and add an ldapidresolver with active directory. then go to audit events and click on any AD-User. The error will occur in the error.log

**Comment by cornelinux** [comment]
How does the Attribute Mapping of your LDAP resolver look like?

**Comment by FloMeyer** [comment]
> How does the Attribute Mapping of your LDAP resolver look like?

Its default:
![image](https://user-images.githubusercontent.com/2670188/112124627-d6e23f80-8bc2-11eb-81e8-c82fecdc92ab.png)

**Comment by plettich** [comment]
Hi @FloMeyer,
could You try if this works for You: https://github.com/privacyidea/privacyidea/issues/2639#issuecomment-791364067

**Comment by FloMeyer** [comment]
Hi @plettich, i tried it.
![image](https://user-images.githubusercontent.com/2670188/112465376-f4e7a580-8d64-11eb-8142-c14cace185d0.png)

But the error still exists in the log. 

```
[2021-03-25 11:21:31,613][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,623][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,624][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,624][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,624][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,624][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,625][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,625][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,625][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,625][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,625][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,626][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,626][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,626][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,626][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,635][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,635][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,635][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,636][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,636][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,636][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,636][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,637][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,637][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,637][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,637][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,637][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,638][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,638][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,638][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,638][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,638][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,647][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,647][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,647][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,648][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,648][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,648][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,648][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,648][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,649][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,649][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,649][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,649][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,650][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,650][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,650][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,650][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,657][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,657][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,657][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,657][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,658][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,658][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,658][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,658][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,659][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,659][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,659][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,659][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,659][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,660][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,660][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,660][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,660][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,671][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,671][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,671][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,672][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,672][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,672][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,672][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,672][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,673][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,673][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,673][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,673][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,673][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,674][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,674][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,674][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,674][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,683][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,683][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,683][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,684][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,684][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,684][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,684][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,685][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,685][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,685][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,685][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,685][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,686][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,686][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,686][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,686][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,695][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,695][734323][139982790244096][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:684] Error during fetching LDAP objects: TypeError("a bytes-like object is required, not 'str'")
[2021-03-25 11:21:31,712][734323][139982890956544][ERROR][privacyidea.lib.user:663] LDAPSocketOpenError("('socket ssl wrapping error: [SSL] internal error (_ssl.c:1123)',)")
[2021-03-25 11:21:32,145][734323][139982790244096][ERROR][privacyidea.lib.user:663] LDAPSocketOpenError("('socket ssl wrapping error: [SSL] internal error (_ssl.c:1123)',)")
```

But! The error in the webui dissapeared.
Before updating the error looked like:
![image](https://user-images.githubusercontent.com/2670188/112465661-43953f80-8d65-11eb-87b6-20a1e37ba7ef.png)


After the update:
![image](https://user-images.githubusercontent.com/2670188/112466179-d7ffa200-8d65-11eb-8b83-d8c10c9ca6b8.png)


The strange thing is: If i click on Refresh in the top right corner, sometime the user info appears and sometime it dissapears. Info there - not there - there - not there. Strange...

And if i go to the userlist, everything works fine - no errors in webui and no errors in log file and all info there:
![image](https://user-images.githubusercontent.com/2670188/112466573-4e9c9f80-8d66-11eb-8377-a10250f9cd3c.png)

**Comment by laclaro** [comment]
We did this in 3.6. I close this issue.
