### ISSUE TITLE
pypi package needs to pin some lower software versions

### ISSUE THREAD

**Issue by deborahgu** [privacyidea/privacyidea#2748]
### Top-level intent

Installing privacyidea from pypi on Ubuntu 20.04 (running under wsl2).

### Steps to reproduce

1. `pip install privacyidea`
2.  in working directory, make `pi.cfg`:
     ```py
    SUPERUSER_REALM = ['super', 'administrators']
    SQLALCHEMY_DATABASE_URI = 'sqlite:////path-to-the-correct-virtualenv-directory/data.sqlite'
    SECRET_KEY = 'Created-according-to-the-documentation'
    PI_PEPPER = 'Created-according-to-the-documentation'
    PI_ENCFILE = '/path-to-the-correct-virtualenv-directory/enckey'
    PI_AUDIT_KEY_PRIVATE = '/path-to-the-correct-virtualenv-directory/private.pem'
    PI_AUDIT_KEY_PUBLIC = '/path-to-the-correct-virtualenv-directory/public.pem'
    ```
2. follow the documentation to set up an admin user:
    ````py
    pi-manage create_enckey
    pi-manage create_audit_keys
    pi-manage createdb
    pi-manage db stamp head -d ~/.virtualenvs/privacyidea/lib/privacyidea/migrations/
    pi-manage admin add admin -e admin@localhost
    ````
3. go to http://localhost:5000/

### Expected outcome

I should be able to log into the web UI with my username and created password.

### Actual outcome

Login fails, and the log has the error message which I have pasted below in the log file section.

### How I fixed this

I had to downgrade PyJWT, which required downgrading several other things, which got more complicated because Flask-Script is no longer supported and hasn't been for several years, so there was a downstream effect from flask-migrate.

```sh
pip uninstall privacyidea Flask flask-script flask-migrate pyjwt
pip install Flask==1.1.2
pip install flask-migrate==2.5.3
pip install pyjwt==1.7.1
pip install privacyidea
```

Then, login worked successfully.

### Configuration

* **privacyIDEA version**:  3.5.2
* **Installation method**: (from Ubuntu packages, github, PyPI, ...) pypi
* **Python version**: 3.8.5
* **Operating system**: Ubuntu 20.04 on wsl2
* **Webserver**:  default werkzeug config
* **Token database**: (MySQL, PostgreSQL, ...) the default sqlite DB, for testing.

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

```
[2021-05-26 16:01:57,105][12176][139733988042560][INFO][privacyidea.api.auth:289] Local admin 'admin' successfully logged in.
[2021-05-26 16:01:57,105][12176][139733988042560][INFO][privacyidea.lib.crypto:821] initializing HSM class: <class 'privacyidea.lib.security.default.DefaultSecurityModule'>
[2021-05-26 16:01:57,105][12176][139733988042560][INFO][privacyidea.lib.crypto:260] Initialized HSM object {'obj': <privacyidea.lib.security.default.DefaultSecurityModule object at 0x7f16554fdee0>}
[2021-05-26 16:01:57,118][12176][139733988042560][INFO][privacyidea.lib.tokens.vasco:56] PI_VASCO_LIBRARY option is not set, functionality disabled
[2021-05-26 16:01:57,147][12176][139733988042560][ERROR][privacyidea.app:1891] Exception on /auth [POST]
Traceback (most recent call last):
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  [Previous line repeated 1 more time]
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 108, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 108, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 108, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  [Previous line repeated 3 more times]
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/lib/event.py", line 99, in event_wrapper
    f_result = func(*args, **kwds)
  File "/home/my-username/.virtualenvs/privacyidea/lib/python3.8/site-packages/privacyidea/api/auth.py", line 363, in get_auth_token
    token = jwt.encode({"username": loginname,
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by cornelinux** [comment]
This is on puporse see the documentation at https://privacyidea.readthedocs.io.
You need to install the requirements.txt.

**Comment by deborahgu** [comment]
the documentation needs to be updated, then. It says you need to install the requirements.txt only for 3.3.3. I installed 3.5.2, so, following the documentation, I only did the `pip install` step.  If this is necessary for versions >= 3.3.3, then the documentation needs to be updated to say so.

**Comment by cornelinux** [comment]
You are basically right.

**Comment by cornelinux** [comment]
See #2750
