### ISSUE TITLE
token-janitor last_auth fails with unknown string format

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2780]
~~~~shell
% sudo privacyidea-token-janitor find --last_auth 30d

+ Reading tokens from database...
INFO:privacyidea.lib.tokens.vasco:PI_VASCO_LIBRARY option is not set, functionality disabled
++ Creating token object list.
Traceback (most recent call last):nd
  File "/usr/bin/privacyidea-token-janitor", line 590, in <module>
    manager.run()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/opt/privacyidea/lib/python3.8/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/bin/privacyidea-token-janitor", line 463, in find
    for tlist in generator:
  File "/usr/bin/privacyidea-token-janitor", line 283, in _get_tokenlist
    if last_auth and token_obj.check_last_auth_newer(last_auth):
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/tokenclass.py", line 1681, in check_last_auth_newer
    last_success_auth = parse_date_string(date_s)
  File "/opt/privacyidea/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/privacyidea/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: hardware
~~~~

**Comment by cornelinux** [comment]
Looks as if I messed up my database and set a lot of tokeninfos to "hardware".
Thus, the time can not be parsed correctly. 

I think we can simply put a try-catch around the data parsing of last_auth. Either

* in the token-janitor or
* in the last_auth lib function.

**Comment by cornelinux** [comment]
Well, I am not sure, if we should really catch this. Because how should we decide if there is a faulty value in `last_auth`.
Should `check_last_auth_newer` return True or False? Based on this an event would be triggered or a token might be deleted.

If at all, we should catch it in the token-janitor and output an error.

**Comment by cornelinux** [comment]
We should catch the error.
If we e.g. search for tokens "older than date", then a token with a faulty date would not match.
If we search for tokens "newer than date", then a token with a faulty date would also not macht.

**Comment by cornelinux** [comment]
I implemented a fix for `check_last_auth_newer`.
Interestingly enough no exception is raised in the token-janitor for `_compare_after` and `_compare_before`.
