### ISSUE TITLE
check policies for valid keys

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2849]
At the moment there are some policies which allow the usage of keys like `{serial}` or `{realm}`.

Typos in policy keys happen quickly.

When the key is used by the code, privacyIDEA throws an according exception, like here for an /token/init with a "tokenlabel="{real}".

```
[2021-08-03 17:40:48,049][6113][140010240476928][ERROR][privacyidea.lib.tokens.hotptoken:292] Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/tokens/hotptoken.py", line 268, in get_init_detail
    extra_data=extra_data)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/apps.py", line 140, in create_google_authenticator_url
    surname=user_obj.info.get("surname", ""))
KeyError: 'real'

[2021-08-03 17:40:48,049][6113][140010240476928][ERROR][privacyidea.lib.tokens.hotptoken:293] failed to set oath or google url: KeyError('real',)
```

To the user this does not provide much information about the incorrect policy. In this case, the frontend user only notices, that the QR-Code of the HOTP token is not displayed during rollout.

It would be nice to catch such errors or to check policies for the supported key words.

**Comment by laclaro** [comment]
Since upon error, it is hard to track down the policy with wrong values, it might be a good idea to check policies with keywords for their correctness at set policy.

**Comment by cornelinux** [comment]
@jona-samuel Please check, if this is still relevant and if we should take action or if we should simply close this.

**Comment by jona-samuel** [comment]
This is still relevant. We can catch the key error and give the user a more detailed error

**Comment by cornelinux** [comment]
Catch the KeyError and raise an Error like

"Unknown Tag (<tag name>) in your policy definition <name of policy>".
