### ISSUE TITLE
PI 2.8 - 2.9 upgrade postgres db issues

### ISSUE THREAD

**Issue by rposton-inmar** [privacyidea/privacyidea#296]
With a functioning 2.8 install running attempting to update to 2.9 fails with db issues if pointing at pgsql as the backend.

    dpkg -s python-privacyidea | grep Version
    Version: 2.8-1trusty

    dpkg -s privacyidea-apache2 | grep Version
    Version: 2.8.1-1trusty

   apt-get install python-privacyidea 

      - no errors 

    dpkg -s python-privacyidea | grep Version
    Version: 2.9-1trusty

But when updating privacyidea-apache2 the installer hangs trying to do some DB update for version_num?

    apt-get install privacyidea-apache2

<pre>
Traceback (most recent call last):
  File "/usr/bin/pi-manage", line 606, in <module>
    manager.run()
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 98, in upgrade
    command.upgrade(config, revision, sql = sql, tag = tag)
  File "/usr/lib/python2.7/dist-packages/alembic/command.py", line 124, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/dist-packages/alembic/script.py", line 199, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/dist-packages/alembic/util.py", line 199, in load_python_file
    module = load_module(module_id, path)
  File "/usr/lib/python2.7/dist-packages/alembic/compat.py", line 55, in load_module
    mod = imp.load_source(module_id, path, fp)
  File "/usr/lib/privacyidea/migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "/usr/lib/privacyidea/migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/usr/lib/python2.7/dist-packages/alembic/environment.py", line 652, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/dist-packages/alembic/migration.py", line 232, in run_migrations
    self._update_current_rev(current_rev, rev)
  File "/usr/lib/python2.7/dist-packages/alembic/migration.py", line 182, in _update_current_rev
    values(version_num=literal_column("'%s'" % new))
  File "/usr/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 76, in _exec
    conn.execute(construct, *multiparams, **params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (InternalError) current transaction is aborted, commands ignored until end of transaction block
 "UPDATE alembic_version SET version_num='20969b4cbf06'" {}
</pre>

** Manually attempting to update the DB schema

    pi-manage db stamp 4f32a4e1bf33 -d /usr/lib/privacyidea/migrations > /dev/null

No handlers could be found for logger "privacyidea.lib.stats"

    pi-manage db upgrade -d /usr/lib/privacyidea/migrations > /dev/null

No handlers could be found for logger "privacyidea.lib.stats"
- hide quoted text -
<pre>
Traceback (most recent call last):
  File "/usr/bin/pi-manage", line 606, in <module>
    manager.run()
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 98, in upgrade
    command.upgrade(config, revision, sql = sql, tag = tag)
  File "/usr/lib/python2.7/dist-packages/alembic/command.py", line 124, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/dist-packages/alembic/script.py", line 199, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/dist-packages/alembic/util.py", line 199, in load_python_file
    module = load_module(module_id, path)
  File "/usr/lib/python2.7/dist-packages/alembic/compat.py", line 55, in load_module
    mod = imp.load_source(module_id, path, fp)
  File "/usr/lib/privacyidea/migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "/usr/lib/privacyidea/migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/usr/lib/python2.7/dist-packages/alembic/environment.py", line 652, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/dist-packages/alembic/migration.py", line 232, in run_migrations
    self._update_current_rev(current_rev, rev)
  File "/usr/lib/python2.7/dist-packages/alembic/migration.py", line 182, in _update_current_rev
    values(version_num=literal_column("'%s'" % new))
  File "/usr/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 76, in _exec
    conn.execute(construct, *multiparams, **params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (InternalError) current transaction is aborted, commands ignored until end of transaction block
 "UPDATE alembic_version SET version_num='20969b4cbf06'" {}
</pre>

Second Attempt... apparently the first run did add some fields to tables.

#: /var/log/privacyidea
<pre>
pi-manage db upgrade -d /usr/lib/privacyidea/migrations
No handlers could be found for logger "privacyidea.lib.stats"
The configuration name is: production
Additional configuration can be read from the file /etc/privacyidea/pi.cfg
Reading Logging settings from /etc/privacyidea/logging.cfg

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/

Could not add the column 'Type' to table tokeninfo
(ProgrammingError) column "Type" of relation "tokeninfo" already exists
 'ALTER TABLE tokeninfo ADD COLUMN "Type" VARCHAR(100)' {}
Could not add column 'condition' to table 'policy'
(InternalError) current transaction is aborted, commands ignored until end of transaction block
 'ALTER TABLE policy ADD COLUMN condition INTEGER NOT NULL' {}
Could not add column 'priority' to table 'resolverrealm'
(InternalError) current transaction is aborted, commands ignored until end of transaction block
 'ALTER TABLE resolverrealm ADD COLUMN priority INTEGER' {}
Could not add the column 'adminrealm' to table policy
(InternalError) current transaction is aborted, commands ignored until end of transaction block
 'ALTER TABLE policy ADD COLUMN adminrealm VARCHAR(256)' {}
Could not add column 'revoked' to table 'token'
(InternalError) current transaction is aborted, commands ignored until end of transaction block
 'ALTER TABLE token ADD COLUMN revoked BOOLEAN NOT NULL' {}
Could not add column 'locked' to table 'token'
(InternalError) current transaction is aborted, commands ignored until end of transaction block
 'ALTER TABLE token ADD COLUMN locked BOOLEAN NOT NULL' {}
- hide quoted text -
Traceback (most recent call last):
  File "/usr/bin/pi-manage", line 606, in <module>
    manager.run()
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 98, in upgrade
    command.upgrade(config, revision, sql = sql, tag = tag)
  File "/usr/lib/python2.7/dist-packages/alembic/command.py", line 124, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/dist-packages/alembic/script.py", line 199, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/dist-packages/alembic/util.py", line 199, in load_python_file
    module = load_module(module_id, path)
  File "/usr/lib/python2.7/dist-packages/alembic/compat.py", line 55, in load_module
    mod = imp.load_source(module_id, path, fp)
  File "/usr/lib/privacyidea/migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "/usr/lib/privacyidea/migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/usr/lib/python2.7/dist-packages/alembic/environment.py", line 652, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/dist-packages/alembic/migration.py", line 232, in run_migrations
    self._update_current_rev(current_rev, rev)
  File "/usr/lib/python2.7/dist-packages/alembic/migration.py", line 182, in _update_current_rev
    values(version_num=literal_column("'%s'" % new))
  File "/usr/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 76, in _exec
    conn.execute(construct, *multiparams, **params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (InternalError) current transaction is aborted, commands ignored until end of transaction block
 "UPDATE alembic_version SET version_num='20969b4cbf06'" {}
</pre>

**** After updates manually reset the alembic_version to the 20969b4cbf06 state, we can pull keys via privacyidea-authorizedkeys, we cant authenticate as we now get a uuencode error see below from sshd

    privacyidea-authorizedkeys username

ssh-rsa AAAA.....keyvalue data   removed........BXfB1bHFIpfu+LnMlb4WHi+EkrIrCoII/tpRDKyIAXCXiPAeR username

auth.log errors:
<pre>
Dec 30 13:55:12 NWSLPIDEA001 sshd[7254]: message repeated 3 times: [ error: key_read: uudecode AAAA.....keyvalue data removed....pBXfB1bHFIpfu+LnMlb4WHi+EkrIrCoII/tpRDKyIAXCXiPAeR e116284\n failed]
</pre>

**Comment by rposton-inmar** [comment]
Postgres version info

$  psql --version
psql (PostgreSQL) 9.4.5

**Comment by rposton-inmar** [comment]
Update:

Authentication errors fixed, it was that I was testing on a dev instance with only 1 key which I manually imported and I mistakenly had imported the putty compatible key not the openssh key version. 

I am able to authenticate now successfully. The update issues are still valid above for remote pg databases I believe as that had nothing to do with the one key loaded for testing.

**Comment by cornelinux** [comment]
Please tell how your **SQLALCHEMY_DATABASE_URI** in the pi.cfg looks like.
Especially what is the driver string.

**Comment by rposton-inmar** [comment]
SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://svcpidev:secretpwd@devpidpg001.domain.com:5432/privacyidea'                                                                                              dpgcp001.inmar.com:5432/privacyidea'
SQLALCHEMY_POOL_SIZE = 20
SQLALCHEMY_POOL_TIMEOUT = 3600
SQLALCHEMY_POOL_RECYCLE = 86400
