### ISSUE TITLE
Port forwarding breaks default config

### ISSUE THREAD

**Issue by AlexFreeland** [privacyidea/privacyidea#2999]
### Top-level intent

Accessing privacyidea via port forwarding with a remote port number other than the standard 443

### Steps to reproduce

1. Install privacyidea
2. Open the web UI from the local machine to verify that it is working
3. Now set up a port forward (iptables, SSH, etc) to this server where the remote port is something other than 443, e.g. `ssh -L 2281:localhost:443 pi-server`
4. Attempt to connect to privacyidea from the remote host
5. Drink in the majesty of the HTTP 500 internal server error

### Expected outcome

The site loads without error

### Actual outcome

The site throws a 500 error.  Looking in `/etc/apache2/error.log` reveals that the culprit is the WSGI module; see the log file section for the relevant snippet.

After some experimentation I found that if I restarted the apache server, and then immediately connected via port forward I could connect as expected.  However, it would then be impossible to connect using port 443... until the server were restarted yet again.  Whichever port number makes the first connection following a restart will work, while all others will yield the HTTP 500 error.

By [default](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIApplicationGroup.html), the WSGI module spins up a new Python sub-interpreter for each "hostname:port" combination.  Seemingly only the first such interpreter is viable while any subsequently created ones fail with the stack trace attached in the log file section.

I don't really have the time or Python experience necessary to interrogate the code base and figure out specifically why this happens, but I did manage to come up with a potential workaround: adding the following line to `/etc/apache2/sites-enabled/privacyidea.conf` will prevent the server from attempting to create multiple sub-interpreters, thereby avoiding the issue:

`WSGIApplicationGroup privacyidea`

### Configuration

* **privacyIDEA version**: privacyidea-apache2 3.6.3-1bionic
* **Installation method**: apt, NetKnights repository
* **Python version**: 3.6
* **Operating system**: Ubuntu 18.04.5 LTS
* **Webserver**: apache2 2.4.29-1ubuntu4.21
* **Token database**: Not sure?  Whatever the default is

### Log file

```
[Tue Feb 08 10:25:50.704304 2022] [wsgi:info] [pid 5105:tid 140677398828800] mod_wsgi (pid=5105): Create interpreter 'localhost:2281|'.
[Tue Feb 08 10:25:50.712011 2022] [wsgi:info] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316] mod_wsgi (pid=5105, process='privacyidea', application='localhost:2281|'): Loading WSGI script '/etc/privacyidea/privacyideaapp.wsgi'.
[Tue Feb 08 10:25:51.232839 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316] mod_wsgi (pid=5105): Target WSGI script '/etc/privacyidea/privacyideaapp.wsgi' cannot be loaded as Python module.
[Tue Feb 08 10:25:51.232902 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316] mod_wsgi (pid=5105): Exception occurred processing WSGI script '/etc/privacyidea/privacyideaapp.wsgi'.
[Tue Feb 08 10:25:51.244004 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316] Traceback (most recent call last):
[Tue Feb 08 10:25:51.244168 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/etc/privacyidea/privacyideaapp.wsgi", line 3, in <module>
[Tue Feb 08 10:25:51.244174 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     from privacyidea.app import create_app
[Tue Feb 08 10:25:51.244180 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/app.py", line 34, in <module>
[Tue Feb 08 10:25:51.244184 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     import privacyidea.api.before_after
[Tue Feb 08 10:25:51.244189 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/before_after.py", line 32, in <module>
[Tue Feb 08 10:25:51.244192 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     from ..lib.user import get_user_from_param
[Tue Feb 08 10:25:51.244197 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/user.py", line 56, in <module>
[Tue Feb 08 10:25:51.244200 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     from .resolver import (get_resolver_object,
[Tue Feb 08 10:25:51.244205 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/resolver.py", line 50, in <module>
[Tue Feb 08 10:25:51.244208 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     from .config import (get_resolver_types, get_resolver_classes, get_config_object)
[Tue Feb 08 10:25:51.244213 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/config.py", line 44, in <module>
[Tue Feb 08 10:25:51.244216 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     from ..models import (Config, db, Resolver, Realm, PRIVACYIDEA_TIMESTAMP,
[Tue Feb 08 10:25:51.244296 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/models.py", line 145, in <module>
[Tue Feb 08 10:25:51.244315 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     class Token(MethodsMixin, db.Model):
[Tue Feb 08 10:25:51.244323 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 67, in __init__
[Tue Feb 08 10:25:51.244327 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     super(NameMetaMixin, cls).__init__(name, bases, d)
[Tue Feb 08 10:25:51.244332 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/flask_sqlalchemy/model.py", line 121, in __init__
[Tue Feb 08 10:25:51.244335 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     super(BindMetaMixin, cls).__init__(name, bases, d)
[Tue Feb 08 10:25:51.244344 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/api.py", line 76, in __init__
[Tue Feb 08 10:25:51.244348 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     _as_declarative(cls, classname, cls.__dict__)
[Tue Feb 08 10:25:51.244353 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in _as_declarative
[Tue Feb 08 10:25:51.244356 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     _MapperConfig.setup_mapping(cls, classname, dict_)
[Tue Feb 08 10:25:51.244361 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 160, in setup_mapping
[Tue Feb 08 10:25:51.244364 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     cfg_cls(cls_, classname, dict_)
[Tue Feb 08 10:25:51.244369 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 194, in __init__
[Tue Feb 08 10:25:51.244372 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     self._early_mapping()
[Tue Feb 08 10:25:51.244377 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 199, in _early_mapping
[Tue Feb 08 10:25:51.244381 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     self.map()
[Tue Feb 08 10:25:51.244386 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 696, in map
[Tue Feb 08 10:25:51.244389 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     self.cls, self.local_table, **self.mapper_args
[Tue Feb 08 10:25:51.244394 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "<string>", line 2, in mapper
[Tue Feb 08 10:25:51.244399 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "<string>", line 2, in __init__
[Tue Feb 08 10:25:51.244404 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
[Tue Feb 08 10:25:51.244407 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     return fn(*args, **kwargs)
[Tue Feb 08 10:25:51.244412 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 721, in __init__
[Tue Feb 08 10:25:51.244425 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     self._configure_properties()
[Tue Feb 08 10:25:51.244432 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1519, in _configure_properties
[Tue Feb 08 10:25:51.244435 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     column_key, column, init=False, setparent=True
[Tue Feb 08 10:25:51.244440 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1757, in _configure_property
[Tue Feb 08 10:25:51.244443 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     prop = self._property_from_column(key, prop)
[Tue Feb 08 10:25:51.244448 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/orm/mapper.py", line 1870, in _property_from_column
[Tue Feb 08 10:25:51.244451 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     columns = util.to_list(prop)
[Tue Feb 08 10:25:51.244456 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 815, in to_list
[Tue Feb 08 10:25:51.244459 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if not isinstance(x, collections_abc.Iterable) or isinstance(
[Tue Feb 08 10:25:51.244464 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/abc.py", line 193, in __instancecheck__
[Tue Feb 08 10:25:51.244468 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     return cls.__subclasscheck__(subclass)
[Tue Feb 08 10:25:51.244473 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Tue Feb 08 10:25:51.244476 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if issubclass(subclass, scls):
[Tue Feb 08 10:25:51.244481 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Tue Feb 08 10:25:51.244484 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if issubclass(subclass, scls):
[Tue Feb 08 10:25:51.244488 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Tue Feb 08 10:25:51.244492 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if issubclass(subclass, scls):
[Tue Feb 08 10:25:51.244496 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   [Previous line repeated 1 more time]
[Tue Feb 08 10:25:51.244501 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/usr/lib/python3.6/typing.py", line 1154, in __subclasscheck__
[Tue Feb 08 10:25:51.244505 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     return super().__subclasscheck__(cls)
[Tue Feb 08 10:25:51.244509 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/abc.py", line 228, in __subclasscheck__
[Tue Feb 08 10:25:51.244512 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if issubclass(subclass, scls):
[Tue Feb 08 10:25:51.244517 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 355, in __subclasscheck__
[Tue Feb 08 10:25:51.244526 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if issubclass(subclass, scls):
[Tue Feb 08 10:25:51.244531 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 355, in __subclasscheck__
[Tue Feb 08 10:25:51.244534 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if issubclass(subclass, scls):
[Tue Feb 08 10:25:51.244539 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 355, in __subclasscheck__
[Tue Feb 08 10:25:51.244542 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if issubclass(subclass, scls):
[Tue Feb 08 10:25:51.244547 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   [Previous line repeated 223 more times]
[Tue Feb 08 10:25:51.244552 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]   File "/opt/privacyidea/lib/python3.6/site-packages/typing_extensions.py", line 350, in __subclasscheck__
[Tue Feb 08 10:25:51.244555 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316]     if self.__extra__ in subclass.__mro__:
[Tue Feb 08 10:25:51.244576 2022] [wsgi:error] [pid 5105:tid 140677398828800] [remote ***REDACTED***:35316] RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by plettich** [comment]
Hi @AlexFreeland thanks for reporting this. Unfortunately i could not reproduce this, talking to privacyIDEA through an SSH tunnel works just fine for me.

According to the backtrace, this looks like something is wrong with the python virtualenv setup. It occurs when it is trying to access the database for the token table.

Could You try a clean installation and check if the issue persists?

**Comment by plettich** [comment]
Ok, just now the error occurred here as well when having two connections through the tunnel. It looks like the mod_wsgi can not differentiate between requests when they come through the tunnel. I'll have to investigate further...

**Comment by AlexFreeland** [comment]
Hi @plettich have you attempted the workaround I gave in the actual outcome section?

**Comment by plettich** [comment]
> Hi @plettich have you attempted the workaround I gave in the actual outcome section?

Yes, it does work for me as well. I still have to figure out, what these ApplicationGroups actually mean and what possible implications are if we add that to the default configuration.
