### ISSUE TITLE
webauthn: having token in init phase blocks other token

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3021]
If a user has a webauthn token that did not complete rollout (Description is "Webauthn initialization"), the other token of the user can not be triggered because a http 500 is returned.

Stacktrace:
```
Exception on /validate/check [GET]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/postpolicy.py", line 108, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/postpolicy.py", line 108, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/postpolicy.py", line 108, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  [Previous line repeated 8 more times]
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/decorators.py", line 41, in function_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  [Previous line repeated 5 more times]
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/decorators.py", line 100, in check_user_or_serial_in_request_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/subscriptions.py", line 334, in check_subscription_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 154, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/event.py", line 99, in event_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/validate.py", line 396, in check
    success, details = check_user_pass(user, password, options=options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 193, in auth_cache
    res, reply_dict = wrapped_function(user_object, passw, options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 261, in auth_user_does_not_exist
    return wrapped_function(user_object, passw, options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 230, in auth_user_has_no_token
    return wrapped_function(user_object, passw, options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 362, in auth_user_timelimit
    res, reply_dict = wrapped_function(user_object, passw, options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 449, in auth_lastauth
    res, reply_dict = wrapped_function(user_or_serial, passw, options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 339, in auth_user_passthru
    return wrapped_function(user_object, passw, options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/log.py", line 194, in log_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/token.py", line 2065, in check_user_pass
    allow_reset_all_tokens=True)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/log.py", line 194, in log_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 645, in reset_all_user_tokens
    r = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/policydecorators.py", line 94, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/challengeresponsedecorators.py", line 150, in generic_challenge_response_reset_pin
    success, reply_dict = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/token.py", line 2391, in check_token_list
    create_challenges_from_tokens(active_challenge_token, reply_dict, options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/token.py", line 2090, in create_challenges_from_tokens
    transactionid=transaction_id, options=options)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/tokens/webauthntoken.py", line 1066, in create_challenge
    user = self._get_webauthn_user(getParam(options, "user", required))
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/tokens/webauthntoken.py", line 763, in _get_webauthn_user
    public_key=webauthn_b64_encode(binascii.unhexlify(self.get_tokeninfo(WEBAUTHNINFO.PUB_KEY))),
TypeError: argument should be bytes, buffer or ASCII string, not 'NoneType'
```

I also don't see any way to complete the initalization from the webui, making the half enrolled webauthn token useless. Maybe a solution would be to delete it if the enrollment is not completed at once?

**Comment by cornelinux** [comment]
We should take care the webauthn tokens are in a corresponding `rollout_state` if they are not readily enrolled.
This way not-readily enrolled webauthn tokens will also be excluded from authentication.

# Todo

Set the rollout_state of the webauthn token after the first step to *client_wait*.

**Comment by nilsbehlen** [comment]
Server version is 3.6.3

With other token i meant other token that generate a challenge. In my case it was an hotp token with the policy that uses them in challenge-response mode. The behavior will probably be the same for push or another webauthn token etc.

I just checked again, it happens with both /validate/check (PIN for both/all token is the same) and /validate/triggerchallenge.
