### ISSUE TITLE
jwt rsplit jwt.exceptions.DecodeError: Not enough segments

### ISSUE THREAD

**Issue by skinkie** [privacyidea/privacyidea#3028]
I guess same as #2601, closed but not solved.

### Top-level intent

What did you try to achieve? Set up push, enroll an user.

### Steps to reproduce

1. Fetching the token /token/?serial=P.... from the browser instead of the app.

### Expected outcome

It should not crash.

### Actual outcome

```
ERROR:privacyidea.app:Exception on /token/ [GET]
Traceback (most recent call last):
  File "/home/skinkie/.local/lib/python3.10/site-packages/jwt/api_jws.py", line 180, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skinkie/.local/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/skinkie/.local/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/skinkie/.local/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/skinkie/.local/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/skinkie/.local/lib/python3.10/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/skinkie/.local/lib/python3.10/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/home/skinkie/.local/lib/python3.10/site-packages/privacyidea/api/auth.py", line 403, in decorated_function
    check_auth_token(required_role=["user", "admin"])
  File "/home/skinkie/.local/lib/python3.10/site-packages/privacyidea/api/auth.py", line 423, in check_auth_token
    r = verify_auth_token(auth_token, required_role)
  File "/home/skinkie/.local/lib/python3.10/site-packages/privacyidea/api/lib/utils.py", line 293, in verify_auth_token
    headers = jwt.get_unverified_header(auth_token)
  File "/home/skinkie/.local/lib/python3.10/site-packages/jwt/api_jws.py", line 166, in get_unverified_header
    headers = self._load(jwt)[2]
  File "/home/skinkie/.local/lib/python3.10/site-packages/jwt/api_jws.py", line 183, in _load
    raise DecodeError('Not enough segments')
jwt.exceptions.DecodeError: Not enough segments
```

### Configuration

* **privacyIDEA version**: 3.6.3
* **Installation method**: pip
* **Python version**: 3.10
* **Operating system**: Linux
* **Webserver**: werkzeug
* **Token database**: PostgreSQL

**Comment by cornelinux** [comment]
Thanks for filing this issue. 
This is not reproducable with the given information.
Currently we do not support Python 3.10. So it might be an issue with 3.10.
We will keep this in mind.

**Comment by skinkie** [comment]
@cornelinux I am happy to try to reproduce it on Python 3.9 on my local machine.

**Comment by plettich** [comment]
If the JWT is broken, we catch the error and throw an AuthError instead.
