### ISSUE TITLE
API error in various endpoints after upgrade to 3.7.1

### ISSUE THREAD

**Issue by Glokeru** [privacyidea/privacyidea#3155]
An upgrade from 3.6.3 to 3.7.1 breaks some endpoints (/user/list or /token) of the API. However other endpoints still work (tested /validate). Trying to list user tokens (which worked in 3.6.3) results in an error:

```
[2022-05-20 09:44:11,668][259501][139924779050752][ERROR][privacyidea.app:1891] Exception on /token/ [GET]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 119, in get_json
    rv = self.json_module.loads(data)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/json/__init__.py", line 253, in loads
    return _json.loads(s, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2267, in process_response
    response = handler(response)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 133, in policy_wrapper
    return self.function(self.request, response, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 169, in sign_response
    request.all_data = get_all_params(request)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/utils.py", line 257, in get_all_params
    if request.json:
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 69, in json
    return self.get_json()
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 128, in get_json
    rv = self.on_json_loading_failed(e)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/wrappers.py", line 27, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
[2022-05-20 09:44:11,677][259501][139924779050752][ERROR][privacyidea.app:1975] Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 119, in get_json
    rv = self.json_module.loads(data)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/json/__init__.py", line 253, in loads
    return _json.loads(s, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2267, in process_response
    response = handler(response)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 133, in policy_wrapper
    return self.function(self.request, response, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 169, in sign_response
    request.all_data = get_all_params(request)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/utils.py", line 257, in get_all_params
    if request.json:
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 69, in json
    return self.get_json()
  File "/opt/privacyidea/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 128, in get_json
    rv = self.on_json_loading_failed(e)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/wrappers.py", line 27, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by plettich** [comment]
@Glokeru this is interesting, these are `GET` requests and should not contain any `json` data. IDK Why `werkzeug` still tries to decode any `json` data here.
Can You specify how You called the endpoints and how You are running privacyIDEA (OS, Webserver, DB)?

**Comment by Glokeru** [comment]
Thanks for your quick reply. We are running PrivacyIDEA on Ubuntu 20.04 behind an Apache Webserver (2.4.41) using MariaDB (10.5.15).  We use the official Netknights Debian Packages (http://lancelot.netknights.it/community/focal/stable). 

This is how we call the endpoints:

`URL: https://privacyidea.mydomain.de/token?user=user1&realm=dau.de

accept: "application/json;charset=UTF-8"
contentType 'application/json;charset=UTF-8'
header 'Accept-Charset', 'UTF-8'
header 'Authorization', XYZ
`

**Comment by plettich** [comment]
Hi @Glokeru 

> This is how we call the endpoints:
> 
> ```
> URL: https://privacyidea.mydomain.de/token?user=user1&realm=dau.de
> 
> accept: "application/json;charset=UTF-8"
> contentType 'application/json;charset=UTF-8'
> header 'Accept-Charset', 'UTF-8'
> header 'Authorization', XYZ
> ```

This is a `GET`-Request which does not contain any data (just the URL parameter). If You remove the `Content-Type` Header from the request, the error should not occur.
