### ISSUE TITLE
PrivacyIDEA access error

### ISSUE THREAD

**Issue by egomett** [privacyidea/privacyidea#3215]
Hello,
I am new to PrivacyIDEA.
I have followed the installation instructions Ubuntu 20.04 (also 18.04) and it has installed perfectly.
I create the admin user and when I try to enter the web page I always have this error:
Authentication failed, 500 Internal Server Error: The server encountered an internal error and was unable to complete you request. Either the server is overloaded or there is an error in the application.
And in /vat/log/privacyidea/privacyidea.log I have this:
[2022-07-10 18:38:44,894][963][140272858367744][INFO][privacyidea.api.auth:289] Local admin 'admin' successfully logged in.
[2022-07-10 18:38:44,899][963][140272858367744][ERROR][privacyidea.app:1891] Exception on /auth [POST]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
    return wrapped_function(*args, **kwds)
  [Previous line repeated 1 more time]
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  [Previous line repeated 3 more times]
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/event.py", line 100, in event_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/api/auth.py", line 350, in get_auth_token
    rights = g.policy_object.ui_get_rights(role, realm, loginname,
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/policy.py", line 1196, in ui_get_rights
    rights = get_static_policy_definitions(scope)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/policy.py", line 2284, in get_static_policy_definitions
    'desc': _("Allow the user to authenticate (default). If set to '{0!s}', "
ValueError: expected ':' after conversion specifier

And I can't get past here.
Thank you very much in advance.

**Comment by plettich** [comment]
Hi @egomett 
are You using a browser with spanish language preference? There is a bug in on of the translation files which causes this error.
Please check if https://github.com/privacyidea/privacyidea/issues/3100#issuecomment-1179021584 helps.

**Comment by egomett** [comment]
Hello,
That is, it seems that the Spanish language does not like.
I have replaced the two files that are commented in help #3100 and it has worked.
Thank you very much for the help.
Greetings to all
