### ISSUE TITLE
Lang problem with ES

### ISSUE THREAD

**Issue by mpikzink** [privacyidea/privacyidea#3239]
### Top-level intent

The WebGUI produces an exception when users try to log in with a Spanish browser.

### Steps to reproduce

1. Set you browser to Spanish (ES)
2. try to login

### Expected outcome

You should be able to login with this Lang or the system should fallback to US

### Actual outcome

Users who like to login with a browser which has a Spanish language get a HTTP/500. So they are not able to login.

### Log file

```
Apache LOG:
ERROR:privacyidea.app:Exception on /auth [POST]
Traceback (most recent call last):
File "/opt/privacyidea/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/privacyidea/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/privacyidea/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/privacyidea/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/opt/privacyidea/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/privacyidea/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
return wrapped_function(*args, **kwds)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
return wrapped_function(*args, **kwds)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/api/lib/prepolicy.py", line 155, in policy_wrapper
return wrapped_function(*args, **kwds)
[Previous line repeated 1 more time]
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
response = wrapped_function(*args, **kwds)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
response = wrapped_function(*args, **kwds)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/api/lib/postpolicy.py", line 109, in policy_wrapper
response = wrapped_function(*args, **kwds)
[Previous line repeated 3 more times]
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/event.py", line 100, in event_wrapper
f_result = func(*args, **kwds)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/api/auth.py", line 352, in get_auth_token
menus = g.policy_object.ui_get_main_menus({"username": loginname,
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
return func(*args, **kwds)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/policy.py", line 1130, in ui_get_main_menus
static_rights = get_static_policy_definitions(role)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
return func(*args, **kwds)
File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/policy.py", line 2285, in get_static_policy_definitions
"the authentication of the user will be denied.").format(AUTHORIZED.DENY),
ValueError: expected ':' after conversion specifier
```

**Comment by plettich** [comment]
Hi @mpikzink this is a known issue. There was a broken string in the community-provided translation.
Please check if this helps: https://github.com/privacyidea/privacyidea/issues/3100#issuecomment-1179021584

**Comment by NNLemling** [comment]
Since it fits thematically, we can clarify and close #3076
