### ISSUE TITLE
host list filter: Failed to detect a valid IP address

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#335]
I'm running 2.10 on Ubuntu 14.04.

In the Machines -> All Machines list I click on Filter in the IP address column and start to enter
an IP address.  I get these messages and a mail with a backtrace from privacyidea.
Since the field doesn't alway contain a valid address, the check should probably get relaxed.

**Comment by jh23453** [comment]
Here's a backtrace I got per mail:
[2016-03-06 18:05:27,918][24697][139954110002944][ERROR][privacyidea.app:1423] Exception on machine [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 96, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/machine.py", line 105, in list_machines_api
    ip = netaddr.IPAddress(ip)
  File "/usr/lib/python2.7/dist-packages/netaddr/ip/__init__.py", line 315, in __init__
    'address from %r' % addr)
AddrFormatError: failed to detect a valid IP address from u':'

**Comment by cornelinux** [comment]
Are you reading machines from LDAP?

**Comment by cornelinux** [comment]
OK. I think this also happens, when you start typing and type

     192.

"192." is also no valid IP address.

**Comment by jh23453** [comment]
Am 2016-03-07 09:38, schrieb Cornelius Kölbel:
> OK. I think this also happens, when you start typing and type
> 
>  192.
> 
> "192." is also no valid IP address.

Yes, that's exactly what I see.

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.

**Comment by jh23453** [comment]
Am 2016-03-07 09:36, schrieb Cornelius Kölbel:
> Are you reading machines from LDAP?

Yes, I read machines from LDAP (right now IPv4), one IPv6 system is in
/etc/privacyidea/hosts.

Jochen

-- 
The only problem with troubleshooting is that the trouble shoots back.
