### ISSUE TITLE
PrivacyIdea is unable to use NTLM bind on Samba DC

### ISSUE THREAD

**Issue by emptythevoid** [privacyidea/privacyidea#3362]
### Top-level intent
I attempted to bind an LDAP Resolver using NTLM to a new Samba-based domain controller and it failed.  Only Simple bind seems to work.

### Steps to reproduce

1. Set up new Samba domain controller (Ubuntu 20.04, Samba 4.13.17) , create users, etc.
2. Set up new PrivacyIdea server.  Test that a Simple LDAP bind works properly.
3. Configure an NTLM bind and perform a Quick Resolver Test. 

### Expected outcome
When tested on a proper Windows server domain, the NTLM bind seemed to work properly with the default Active Directory settings.  Test was successful and objects were returned.  When tested on a Samba domain, this failed (see below)

### Actual outcome
PrivacyIdea complains that "session terminated by server."  The Samba domain controller logs show an "LDAP_PROTOCOL_ERROR" when the attempt is made.  

The privacyidea.log shows this when Quick Resolver Test is performed:

~~~~log
[2022-11-03 15:18:25,423][722][139847064409856][DEBUG][privacyidea.lib.resolver:185] Entering pretestresolver with arguments ('ldapresolver', {'SIZELIMIT': 1, 'TIMEOUT': 5, 'UIDTYPE': 'objectGUID', 'type': 'ldapresolver', 'AUTHTYPE': 'NTLM', 'SCOPE': 'SUBTREE', 'CACHE_TIMEOUT': 120, 'NOSCHEMAS': False, 'TLS_VERIFY': False, 'TLS_VERSION': '2', 'START_TLS': True, 'SERVERPOOL_ROUNDS': 2, 'SERVERPOOL_SKIP': 30, 'LDAPURI': 'ldap://192.168.122.70', 'LDAPBASE': 'dc=samba,dc=lan', 'BINDDN': 'SAMBA\\privacy', 'LOGINNAMEATTRIBUTE': 'sAMAccountName', 'LDAPSEARCHFILTER': '(sAMAccountName=*)(objectClass=person)', 'USERINFO': '{ "phone" : "telephoneNumber", "mobile" : "mobile", "email" : "mail", "surname" : "sn", "givenname" : "givenName" }', 'NOREFERRALS': True, 'EDITABLE': False, 'BINDPW': 'redacted', 'resolver': 'ntlm'}) and keywords {}
[2022-11-03 15:18:25,423][722][139847064409856][DEBUG][privacyidea.lib.resolver:185] Entering get_resolver_list with arguments () and keywords {'filter_resolver_name': 'ntlm'}
[2022-11-03 15:18:25,423][722][139847064409856][DEBUG][privacyidea.lib.resolver:200] Exiting get_resolver_list with result HIDDEN
[2022-11-03 15:18:25,424][722][139847064409856][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:184] Get LDAP schema info: 'SCHEMA'
[2022-11-03 15:18:25,424][722][139847064409856][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:917] Added 192.168.122.70, None, False to server pool.
[2022-11-03 15:18:25,433][722][139847064409856][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:1320] Doing start_tls
[2022-11-03 15:18:25,446][722][139847064409856][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:1098] Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 1057, in testconnection
    if not l.bind():
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/core/connection.py", line 621, in bind
    response = self.do_ntlm_bind(controls)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/core/connection.py", line 1367, in do_ntlm_bind
    response = self.post_send_single_response(self.send('bindRequest', request, controls))
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/sync.py", line 121, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/opt/privacyidea/lib/python3.8/site-packages/ldap3/strategy/base.py", line 369, in get_response
    raise LDAPSessionTerminatedByServerError(self.connection.last_error)
ldap3.core.exceptions.LDAPSessionTerminatedByServerError: session terminated by server

[2022-11-03 15:18:25,446][722][139847064409856][DEBUG][privacyidea.lib.resolver:198] Exiting pretestresolver with result (False, "LDAPSessionTerminatedByServerError('session terminated by server')")
[2022-11-03 15:18:25,447][722][139847064409856][DEBUG][privacyidea.api.resolver:198] Exiting test_resolver with result <PiResponseClass 264 bytes [200 OK]>
[2022-11-03 15:18:25,450][722][139847064409856][DEBUG][privacyidea.api.lib.utils:258] Update params in request POST https://192.168.122.71/resolver/test with JSON data.
[2022-11-03 15:18:25,515][722][139847064409856][DEBUG][privacyidea.api.before_after:100] End handling of request '/resolver/test?'
~~~~

### Configuration

* **privacyIDEA version**:  3.7.4-1focal
* **Installation method**: From Ubuntu Packages
* **Python version**:  3.8.10
* **Operating system**: Ubuntu 20.04
* **Webserver**: apache
* **Token database**: MySQL (whatever is the default PrivacyIdea sets up)

### Other
I realize that this is probably an issue caused by Samba, but I'm not sure how to troubleshoot this further.
On the Samba domain controller, I have tested the following custom directives in /etc/samba/smb.conf to try to lessen the default security levels, but these did not appear successful:
ntlm auth = yes
lanman auth = no
client lanman auth = no
ldap server require string auth = No
clietn ldap sasl wrapping = plain
tls verify peer = no_check
server signing = auto

The only progress I was able to make was with running ldapsearch against the Samba domain controller. Initially this failed with  "stringer authentication required. Sign or sealed are required."  After setting ldap server require strong auth = No, ldapsearch was able to return results over NTLM, but this made no difference for PrivacyIdea.

**Comment by cornelinux** [comment]
privacyIDEA uses the python ldap3 module.
It is not clear, if privacyIDEA uses the module in a wrong way (which does not seem this way, since it works with AD), if this is a problem in the python ldap3 module or a problem in the samba server.

So it is even not clear, if there is anything that needs to be fixed **in** privacyIDEA or if privacyIDEA might need to work around other software's problems.

In version 3.8 the ldap resolver will be able to also connect via kerberos - for those who do not want to do simple bind via TLS.
Thus I would not like to put a lot of effort into this, since there is no bright future for NTLM, imho.

Maybe you could file a question at a samba4 forum with the server log which could at least shed some light, if ldap3 or privacyIDEA is doing anything wrong.

**Comment by emptythevoid** [comment]
This is fair - i wasn't sure where to file this anyway.  For my purposes, if kerberos becomes an option, I won't need to use NTLM, so that's fine.  Thanks for responding.
