### ISSUE TITLE
MS CA connector: Exception without SSL

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3460]
When trying to set up a MS CA connector without the use of SSL, the following exception is thrown:

[ERROR][privacyidea.app:1892] Exception on /caconnector/specific/microsoft [GET]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/lib/prepolicy.py", line 157, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/api/caconnector.py", line 70, in get_caconnector_specific
    res = get_caconnector_specific_options(catype, param)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/log.py", line 155, in log_wrapper
    return func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.6/site-packages/privacyidea/lib/caconnector.py", line 174, in get_caconnector_specific_options
    c_obj = c_obj_class("dummy", data)
TypeError: 'NoneType' object is not callable

The IP/Hostname and port are reachable from the privacyidea server. Version is 3.8.

**Comment by cornelinux** [comment]
THe problem is, that ubuntu 18 does provide the right python version with provides the correct version of grpc.

**Comment by cornelinux** [comment]
Provide better error message.
