### ISSUE TITLE
sending test email for email server raises authentication error using plain auth

### ISSUE THREAD

**Issue by mgisbers** [privacyidea/privacyidea#350]
When trying to test a smtpserver configuration using git trunk version, I always get an authorization error on the mailserver and in privacyidea.log when using an plain auth.

I made sure credentials are correct and logging in 'by hand' works as expected.

privacyidea.log:
```
SMTPAuthenticationError: (535, '5.7.8 Error: authentication failed:')
[2016-03-28 19:55:39,479][30338][140453494273792][WARNING][privacyidea.lib.crypto:326] 'NoneType' object has no attribute 'find'
[2016-03-28 19:55:41,528][30338][140453494273792][ERROR][privacyidea.app:1423] Exception on /smtpserver/send_test_email [POST]
Traceback (most recent call last):
  File "/opt/privacyidea/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/privacyidea/api/lib/prepolicy.py", line 96, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/privacyidea/lib/log.py", line 125, in log_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/privacyidea/api/smtpserver.py", line 146, in test
    "The configuration %s is working." % identifier)
  File "/opt/privacyidea/privacyidea/lib/smtpserver.py", line 93, in test_email
    mail.login(config.username, password)
  File "/usr/lib/python2.7/smtplib.py", line 613, in login
    raise SMTPAuthenticationError(code, resp)
```

mailserver (IPv6 address scrambled):
```
Mär 28 19:58:18 mx postfix/smtpd[3491]: connect from unknown[::abcd:]
Mär 28 19:58:18 mx postfix/smtpd[3491]: Anonymous TLS connection established from unknown[::abcd]: TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Mär 28 19:58:20 mx postfix/smtpd[3491]: warning: unknown[::abcd]: SASL PLAIN authentication failed:
Mär 28 19:58:20 mx postfix/smtpd[3491]: lost connection after AUTH from unknown[::abcd]
```

All packages needed for installation and requirements.txt are installed.

Any hints?

**Comment by cornelinux** [comment]
Thanks for the error output!

The line

[2016-03-28 19:55:39,479][30338][140453494273792][WARNING][privacyidea.lib.crypto:326] 'NoneType' object has no attribute 'find'

indicates, that the password could not be decrypted. 

Digging into it I realize, that the password can not be decrypted, since - in case of the test run - it is no encrypted! :-/

Anyway, if you save the smtpserver it should work.

Will upload a fix soon.

**Comment by mgisbers** [comment]
You are right.

I saved the configuration and tried an email token. It works.

**Comment by cornelinux** [comment]
You can pull the update. The fix is a 1,5-liner. (Most code are the tests ;-)
With the update the TEST should also run.

**Comment by mgisbers** [comment]
After applying the fix it works for the entered password.

If you pick an already configured smtpserver from list, enter a destination email and click on test e-mail an error is raised because there is no password. Would be nice to have hint and disable the test e-mail button unless there is a manual entered password.
