### ISSUE TITLE
SMS OTP based on AD LDAP query and SMS gateway with GET request ends with KeyError: 'mobile'

### ISSUE THREAD

**Issue by LeadManPL** [privacyidea/privacyidea#3591]
### Top-level intent
Send SMS OTP based on AD LDAP query and SMS gateway with GET request

### Steps to reproduce
1. Configure SMS gateway with Providermodule privacyidea.lib.smsprovider.HttpSMSProvider.HttpSMSProvider
2. define Options, with following, or other options depending on your SMS gateway setup - the important one is {mobile}:
    - login=your_user_admin
    - message="Your SMS OTP Token value is {otp}" 
    - pass=your_password
    - to={mobile}
3. Set **mobile phone** number of AD LDAP user to something real to get that number from AD
4. Create new SMS OTP token for your user
5. Go to  Tokens -> details -> Test token

### Expected outcome
Get an SMS on my mobile phone

### Actual outcome
PrivacyIDEA gets data from AD properly, using field {mobile} (in this log output it is 111222333), then gets an error trying to use {phone} instead of {mobile} - see log for details - end generates error: **KeyError: 'mobile'**

**I was able to workaround this issue by using {phone} instead of {mobile} and setting phone number in AD into field for land line number**, but this is not feasible because other sources are enriched with data from that AD, and land line field is used for other purpose

### Configuration

* **privacyIDEA version**: 3.8.1
* **Installation method**: Ubuntu packages
* **Python version**: 
```
python3 --version
Python 3.10.6
 ```
* **Operating system**: PRETTY_NAME="Ubuntu 22.04.2 LTS"
* **Webserver**: apache2
* **Token database**: I do not have token database SMS OTP is generated by privacyIDEA

### Log file

<details>
<summary>The log output</summary>

```log
[2023-04-12 11:49:54,854][4113][140162022254144][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:275] Reading '53938bd8-5645-4be3-b84c-0e83a645bd61' from cache for 'getUserInfo'
[2023-04-12 11:49:54,856][4113][140162022254144][DEBUG][privacyidea.lib.config:181] Entering get_from_config with arguments ('sms.identifier',) and keywords {}
[2023-04-12 11:49:54,857][4113][140162022254144][DEBUG][privacyidea.lib.config:194] Exiting get_from_config with result EagleSMS
[2023-04-12 11:49:54,858][4113][140162022254144][DEBUG][privacyidea.lib.utils:1209] klass: <class 'privacyidea.lib.smsprovider.HttpSMSProvider.HttpSMSProvider'>
[2023-04-12 11:49:54,859][4113][140162022254144][DEBUG][privacyidea.lib.tokens.smstoken:468] submitMessage: '965545', to phone '111222333'
[2023-04-12 11:49:54,859][4113][140162022254144][DEBUG][privacyidea.lib.smsprovider.HttpSMSProvider:81] submitting message '965545' to 111222333
[2023-04-12 11:49:54,890][4113][140162022254144][WARNING][privacyidea.lib.tokens.smstoken:358] The PIN was correct, but the SMS could not be sent! (KeyError('mobile'))
[2023-04-12 11:49:54,890][4113][140162022254144][DEBUG][privacyidea.lib.tokens.smstoken:359] Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/tokens/smstoken.py", line 341, in create_challenge
    success, sent_message = self._send_sms(
  File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/log.py", line 190, in log_wrapper
    f_result = func(*args, **kwds)
  File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/tokens/smstoken.py", line 469, in _send_sms
    ret = sms.submit_message(phone, message)
  File "/opt/privacyidea/lib/python3.10/site-packages/privacyidea/lib/smsprovider/HttpSMSProvider.py", line 102, in submit_message
    parameter[k] = v.format(otp=message, phone=phone)
KeyError: 'mobile'

[2023-04-12 11:49:54,891][4113][140162022254144][DEBUG][privacyidea.lib.tokens.smstoken:194] Exiting create_challenge with result (False, 'The PIN was correct, but the SMS could not be sent!', None, {'attributes': {'state': None, 'valid_until': '2023-04-12 11:50:54.891569'}})
[2023-04-12 11:49:54,892][4113][140162022254144][DEBUG][privacyidea.lib.token:194] Exiting check_token_list with result (False, {'multi_challenge': [], 'message': 'The PIN was correct, but the SMS could not be sent!', 'messages': ['The PIN was correct, but the SMS could not be sent!'], 'transaction_ids': []})
[2023-04-12 11:49:54,892][4113][140162022254144][DEBUG][privacyidea.lib.token:194] Exiting check_serial_pass with result (False, {'multi_challenge': [], 'message': 'The PIN was correct, but the SMS could not be sent!', 'messages': ['The PIN was correct, but the SMS could not be sent!'], 'transaction_ids': []})
[2023-04-12 11:49:54,892][4113][140162022254144][DEBUG][privacyidea.lib.auditmodules.base:181] Entering log with arguments (<privacyidea.lib.auditmodules.sqlaudit.Audit object at 0x7f79ec826c80>, {'info': 'The PIN was correct, but the SMS could not be sent!', 'success': False, 'serial': '', 'token_type': None}) and keywords {}
[2023-04-12 11:49:54,893][4113][140162022254144][DEBUG][privacyidea.lib.auditmodules.base:194] Exiting log with result None
```
</details>

**Comment by cornelinux** [comment]
@LeadManPL  Please check your resolver, that it uses the correct mapping of your attributes. "mobile" needs to map to the correct AD attribute.

@plettich I think in the past the tag for SMS was "phone" which used the mobile number. I am not sure, if the tagging has changed in this way, that it uses the privacyidea user attributes.

**Comment by jona-samuel** [comment]
You have to use 'to={phone}' not 'to={mobile}'. Hir isn't 'phone' the 'phone' from LDAP, it's just the tag for the phone number the SMS is submitted to in your case: '111222333'.

**Comment by LeadManPL** [comment]
Hi @cornelinux , we decided to go wit localSQL resolver approach and removed LDAP configuration, so sorry but I 'm not able to check LDAP anymore.

However I have found part of screenshot i made during testing of LDAP, and most likely it was set up as on following picture marked in red. Is this proper mapping?

![privacyidea_issue_3591_2023-05-11_13-14](https://github.com/privacyidea/privacyidea/assets/13769051/8696b20c-e501-4d72-9000-d1a129d0941e)


 If this issue was related to my specific configuration, feel free to close this ticket.

**Comment by cornelinux** [comment]
Thanks. This is simply confusing.

The SMS Provider only accepts the tag "{phone}" in the *to* field.
However, this is the *mobile* key from the resolver, as @jona-samuel mentioned.

This is by the way the same way with the SQL resolver. It will also pass the contents from the resolver "mobile" to the "phone" tag in the SMS provider.

**Comment by LeadManPL** [comment]
Ok, so you say if my localSQL resolver has mapping as:
```
{"userid": "id", "username": "username", "email":"email", "password": "password", "phone":"phone", "mobile":"mobile", "surname":"surname", "givenname":"givenname", "description": "description"}
```
it means I can use {mobile} ?

**Comment by jona-samuel** [comment]
Only two tags in the HTTP provider are allowed '{otp}' and '{phone}'. ’{phone}' gives you the number the SMS is sent to (You can see this in the log). You can't configure the used number in the HTTP provider. If the number is in your token or event handler correct, then you can use {phone}, else you have to change it token/event handler. But you said "privacyIDEA gets data from AD properly, using field {mobile} (in this log output it is 111222333)", so you can just use '{phone}' in the provider and you get the same number you see in the log.
