### ISSUE TITLE
Problems with webhook handler module

### ISSUE THREAD

**Issue by bpnx** [privacyidea/privacyidea#3676]
### Top-level intent

User the Webhook handler module

### Steps to reproduce

1. create a new event based on auth Eg.:

{   'event': [   {   'action': 'post_webhook',
                     'active': True,
                     'condition': '',
                     'conditions': {},
                     'event': ['auth'],
                     'handlermodule': 'WebHook',
                     'id': 12,
                     'name': 'webhook_post_auth',
                     'options': {   'URL': 'http://localhost:9000/hooks/webhook',
                                    'content_type': 'json',
                                    'data': 'fake data',
                                    'replace': 'False'},
                     'ordering': 0,
                     'position': 'post'}]}

### Expected outcome

Some data should arrive to http://localhost:9000/hooks/webhook

### Actual outcome

When a user tries to authenticate, authentication fails.
No data is sent, I've used a network sniffer to be sure.

### Configuration

* **privacyIDEA version**: 3.8.1
* **Installation method**: pip3
* **Python version**: 3.9.2
* **Operating system**: Linux (Debian 11.7)
* **Webserver**: apache 2.4.56-1~deb11u2
* **Token database**: MySQL

### Log file

~~~~
[2023-07-06 10:12:18,249][413205][140129874433792][ERROR][privacyidea.app:1891] Exception on /auth [POST]
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/privacyidea/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/privacyidea/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/privacyidea/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/privacyidea/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/privacyidea/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/api/lib/prepolicy.py", line 158, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/api/lib/prepolicy.py", line 158, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/api/lib/prepolicy.py", line 158, in policy_wrapper
    return wrapped_function(*args, **kwds)
  [Previous line repeated 2 more times]
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/api/lib/postpolicy.py", line 112, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/api/lib/postpolicy.py", line 112, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/api/lib/postpolicy.py", line 112, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  [Previous line repeated 3 more times]
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/lib/event.py", line 134, in event_wrapper
    event_handler.do(e_handler_def.get("action"),
  File "/opt/privacyidea/lib/python3.9/site-packages/privacyidea/lib/eventhandler/webhookeventhandler.py", line 133, in do
    user = User(login=g.logged_in_user.get('username'),
  File "/opt/privacyidea/lib/python3.9/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'logged_in_user'
~~~~

**Comment by plettich** [comment]
Hi @bpnx while we are working on a fix to avoid the error, there is also a logical issue in the request. The `/auth` endpoint does not provide a `logged-in user` in the request since the logging-in is currently done is this request. Only if a request with a valid `PI-Authorization` header is sent, the logged-in user is set to the user in the JWT.
