### ISSUE TITLE
Schema upgrade on PostgreSQL fails for 3.9 + off-by-one bug

### ISSUE THREAD

**Issue by jsaathof** [privacyidea/privacyidea#3778]
### Top-level intent

I am trying to upgrade from 3.8.1 to 3.9. The database schema upgrade fails because a sequence is created that already exists. There is a try-except clause in the upgrade script (migrations/versions/5cb310101a1f_.py) but that script assumes that the script can continue when a sequence is created that already exists. This is not true dut ot the use of a transaction, which is good on its own.
```
2023-10-04 21:59:18.536 CEST privacyidea privacyidea [30093]ERROR:  relation "caconnector_seq" already exists
2023-10-04 21:59:18.536 CEST privacyidea privacyidea [30093]STATEMENT:  CREATE SEQUENCE caconnector_seq INCREMENT BY 1 START WITH 2
2023-10-04 21:59:18.541 CEST privacyidea privacyidea [30093]ERROR:  current transaction is aborted, commands ignored until end of transaction block
```
This is reported back to the upgrade script but that errors out.
```
(venv)
[server2]:/opt/privacyidea
root# ./pi-manage db upgrade -d /opt/privacyidea/migrations 5cb310101a1f

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/
                                           vunknown

Running online
CurrentID in Table authcache: 1
 +++ Creating Sequence: authcache_seq
CurrentID in Table caconnector: 1
 +++ Creating Sequence: caconnector_seq
Traceback (most recent call last):
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/privacyidea-3.9/./pi-manage", line 1739, in <module>
    manager.run()
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/privacyidea/migrations/env.py", line 110, in <module>
    run_migrations_online()
  File "/opt/privacyidea/migrations/env.py", line 100, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/opt/privacyidea-3.9/migrations/versions/5cb310101a1f_.py", line 51, in upgrade
    current_id = session.query(func.max(tbl.c.id)).one()[0] or 1
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/privacyidea/venv/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block

[SQL: SELECT max(challenge.id) AS max_1
FROM challenge]
(Background on this error at: https://sqlalche.me/e/14/2j85)
```
It actually looks like the script encounters an isssue while running the query on the next table (the challenge table in this output) but it is not. The error in the PostgreSQL log shows the error comes from the creation of the sequence which already exists.

The upgrade script actually does not seem to check if the sequence already exist.

Now another issue I see here it that the new sequence is started with a value of 2. That comes from the code that looks up the last id in the table. If no value is found the value is set to 1. Later 1 is added to this value. This results in a start value of 2 which is weird. The value should be set to 0 if no results are found.

### Steps to reproduce

1. Upgrade the software
2. upgrade the database schema with `tools/privacyidea-schema-upgrade /opt/privacyidea/migrations`

### Expected outcome

Upgrade of the database schema to revision 5cb310101a1f

### Actual outcome

The schema was not upgraded and the transaction was cancelled.

### Configuration

* **privacyIDEA version**: 3.9
* **Installation method**: Github source with venv
* **Python version**: Python 3.10.13
* **Operating system**: OpenSUSE Leap 15.5
* **Webserver**: Nginx 1.21.5 with uWSGI 2.0.22
* **Token database**: PostgreSQL 15

### Log file

**Set PI_LOGLEVEL = logging.DEBUG in pi.cfg and take a look at the privacyidea.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by plettich** [comment]
Hi @jsaathof 
how does Your `SQLALCHEMY_DATABASE_URI` looks like?
It should start with `postgresql+psycopg2://...` otherwise You'll run into the above mentioned transaction failure.

We already noticed the off-by-one but decided to keep it since it should not pose any problems. We do not assume anywhere that indices start at 1.

**Comment by jsaathof** [comment]
This was indeed not the case. I have changed this and the database upgrade was done. I'm not shure why the psycopg2 was not there. I think I had that configured.

And I understand that the index can start at two but my OCD is kicking in here.

**Comment by plettich** [comment]
@jsaathof 
sorry for triggering Your OCD ;-) We'll fix this in the upcoming patch release.
