### ISSUE TITLE
String Comparsion in HOSTS Resolver returns if substring matches and not if string is equal

### ISSUE THREAD

**Issue by splattner** [privacyidea/privacyidea#484]
I have a HOSTS Resolver with the following enties

```
10.5.16.50     proxy proxy.rdit.ch
10.5.12.30     rproxy-node1 rproxy-node1.rdit.ch
10.5.12.31     rproxy-node2 rproxy-node2.rdit.ch
```
which gives me this Machine Config:

![auswahl_002](https://cloud.githubusercontent.com/assets/3875381/17548658/2b4b2cb0-5eed-11e6-9b5b-99566ca7e54e.png)

On the proxy machine I run:

`/usr/bin/privacyidea-authorizedkeys root`

and I get:

```
/usr/bin/privacyidea-authorizedkeys root
Traceback (most recent call last):
  File "/usr/bin/privacyidea-authorizedkeys", line 117, in <module>
    main()
  File "/usr/bin/privacyidea-authorizedkeys", line 96, in main
    response = client.get("/machine/authitem/ssh", params)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 142, in get
    return self._send_response(r)
  File "/usr/lib/python2.7/dist-packages/privacyideautils/clientutils.py", line 101, in _send_response
    description=r.text)
PrivacyIDEAClientError: u'ERR500: {"jsonrpc": "2.0", "signature": "14653092100614736010088457383259881539202493586224338621649001645219959443972052141588162673037075979333491233407065095751768684306183359472106512182301522993318275863974829881570173164636833726559851346639811831652663759627075125164775519830899313252249191387285325747031091591522279227367078892410914748883399454687674513728754073007710754074303432514715583225083866384925704264808718381104925057969520000206006854355941235653971895834094783312712730962636861615617647288777212756624373365627635173033050457118448627697513752768825951741796796928626347521473873544258310222841993772217509584196754180397361890446455", "detail": null, "version": "privacyIDEA 2.13", "result": {"status": false, "error": {"message": "Can not get unique ID for hostname=u\'proxy\' and IP=None. More than one machine found.", "code": -500}}, "time": 1470821164.827561, "id": 1}'

Error: u'ERR500: {"jsonrpc": "2.0", "signature": "14653092100614736010088457383259881539202493586224338621649001645219959443972052141588162673037075979333491233407065095751768684306183359472106512182301522993318275863974829881570173164636833726559851346639811831652663759627075125164775519830899313252249191387285325747031091591522279227367078892410914748883399454687674513728754073007710754074303432514715583225083866384925704264808718381104925057969520000206006854355941235653971895834094783312712730962636861615617647288777212756624373365627635173033050457118448627697513752768825951741796796928626347521473873544258310222841993772217509584196754180397361890446455", "detail": null, "version": "privacyIDEA 2.13", "result": {"status": false, "error": {"message": "Can not get unique ID for hostname=u\'proxy\' and IP=None. More than one machine found.", "code": -500}}, "time": 1470821164.827561, "id": 1}'
```

as soon as I remove rproxy-node1 and rproxy-node2:

```
10.5.16.50      proxy proxy.rdit.ch
#10.5.12.30     rproxy-node1 rproxy-node1.rdit.ch
#10.5.12.31     rproxy-node2 rproxy-node2.rdit.ch
```

the result is fine

```
/usr/bin/privacyidea-authorizedkeys root
ssh-rsa AAAAB3NzaC1yc.... sebastianplattner
```

Here's the log output on the privacyidea server:

```
xception on /machine/authitem/ssh [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 104, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 104, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/machine.py", line 366, in get_auth_items_api
    application=application, challenge=challenge,
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/machine.py", line 404, in get_auth_items
    application=application)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 180, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/machine.py", line 290, in list_machine_tokens
    resolver_name)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/machine.py", line 359, in _get_host_identifier
    (machine_id, resolver_name) = get_machine_id(hostname)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/machine.py", line 117, in get_machine_id
    "More than one machine found." % (hostname, ip))
Exception: Can not get unique ID for hostname=u'proxy' and IP=None. More than one machine found.
```

Some observations:

IP seems to be None, not sure why this is not set, I guess its set here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/machine.py#L364

But why is it None?

But...

To me it seems that the get_machines code in https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machines/hosts.py#L37 is the problem
or more precise this one here https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/machine.py#L72
you set substring=True

which leads to returning all machine which have the substring in it
therefore "proxy" returns "proxy" & "rproxy-node1" & rproxy-node2"

Is this by intention?

**Comment by cornelinux** [comment]
This is probably not the intention. I will start with writing a test....

**Comment by cornelinux** [comment]
Thanks a lot for the detailed analysis. I was able to fix this issue in a few lines. The substring is used for searching hosts. Of course in this scenario, we want to use subscring=False.
