### ISSUE TITLE
SQL error with 2.15

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#508]
privacyIDEA:
Installation method:- [ ] Ubuntu
Webserver: apache

# What did you try to do?
I did some tests after upgrading Ubuntu to 16.04 and Privacyidea to 2.15.
I got the following messages in my mail:
[2016-10-06
22:40:38,006][9713][140671719589632][ERROR][privacyidea.lib.auditmodules.sqlaudit:266]
DATA: {'info': False, 'success': True, 'privacyidea_server':
'athene.jochen.org', 'client_user_agent': 'chrome', 'client':
'fd23:e163:19f7:1234:9c9a:c968:83c5:6629', 'action_detail': '',
'action': 'GET /register'}
[2016-10-06
22:40:38,006][9713][140671719589632][ERROR][privacyidea.lib.auditmodules.sqlaudit:266]
DATA: {'info': False, 'success': True, 'privacyidea_server':
'athene.jochen.org', 'client_user_agent': 'chrome', 'client':
'fd23:e163:19f7:1234:9c9a:c968:83c5:6629', 'action_detail': '',
'action': 'GET /register'}

# What outcome did you expect?
no error mails :-)

My current guess is that field client in table pidea_audit is too small.
My IPv6 addressesn are longer than 20 characters:

mysql> describe pidea_audit
    -> ;
+--------------------+--------------+------+-----+---------+----------------+
| Field              | Type         | Null | Key | Default | Extra          |
+--------------------+--------------+------+-----+---------+----------------+
| id                 | int(11)      | NO   | PRI | NULL    | auto_increment |
| date               | datetime     | YES  |     | NULL    |                |
| signature          | varchar(620) | YES  |     | NULL    |                |
| action             | varchar(50)  | YES  |     | NULL    |                |
| success            | int(11)      | YES  |     | NULL    |                |
| serial             | varchar(20)  | YES  |     | NULL    |                |
| token_type         | varchar(12)  | YES  |     | NULL    |                |
| user               | varchar(20)  | YES  |     | NULL    |                |
| realm              | varchar(20)  | YES  |     | NULL    |                |
| administrator      | varchar(20)  | YES  |     | NULL    |                |
| action_detail      | varchar(50)  | YES  |     | NULL    |                |
| info               | varchar(50)  | YES  |     | NULL    |                |
| privacyidea_server | varchar(20)  | YES  |     | NULL    |                |
| client             | varchar(20)  | YES  |     | NULL    |                |
| loglevel           | varchar(12)  | YES  |     | NULL    |                |
| clearance_level    | varchar(12)  | YES  |     | NULL    |                |
+--------------------+--------------+------+-----+---------+----------------+
16 rows in set (0,00 sec)

**Comment by cornelinux** [comment]
You are probably right! So migrate to IPv4 ;-)

Please update the field lenght

    mysql> alter table pidea_audit modify client varchar(50);

Bummer - at the moment there is no real migration process/script for the audit table....

**Comment by jh23453** [comment]
Won't "upgrade" to IPv4 :-)

alter column to varchar(50) works as expected - thanks.

But now I get another message:
[2016-10-10 22:08:34,393][14008][140592141522688][ERROR][privacyidea.lib.auditmodules.sqlaudit:265] exception AttributeError("'User' object has no attribute 'translate'",)
[2016-10-10 22:08:34,524][14008][140592141522688][ERROR][privacyidea.lib.auditmodules.sqlaudit:266] DATA: {'info': '', 'tokentype': u'yubikey', 'success': 1, 'privacyidea_server': 'athene.jochen.org', 'client_user_agent': None, 'client': 'fd23:e163:19f7:1234:216:3eff:fe1a:ac40', 'user': User(login='', realm='', resolver=''), 'action_detail': '', 'action': 'GET /ttype/<ttype>', 'serial': None}

**Comment by cornelinux** [comment]
If you turn on debug, a traceback will be written to the log file:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/auditmodules/sqlaudit.py#L267

**Comment by jh23453** [comment]
Here's the traceback:
[2016-10-11 06:44:20,925][20036][139633224001280][DEBUG][privacyidea.lib.auditmodules.sqlaudit:267] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/auditmodules/sqlaudit.py", line 256, in finalize_log
    self.session.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 813, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 156, in execute
    query = self.mogrify(query, args)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 135, in mogrify
    query = query % self._escape_args(args, conn)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 115, in _escape_args
    return dict((key, conn.escape(val)) for (key, val) in args.items())
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 115, in <genexpr>
    return dict((key, conn.escape(val)) for (key, val) in args.items())
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 781, in escape
    return escape_item(obj, self.charset, mapping=mapping)
  File "/usr/lib/python2.7/dist-packages/pymysql/converters.py", line 26, in escape_item
    val = encoder(val, mapping)
  File "/usr/lib/python2.7/dist-packages/pymysql/converters.py", line 109, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/usr/lib/python2.7/dist-packages/pymysql/converters.py", line 72, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'User' object has no attribute 'translate'

**Comment by cornelinux** [comment]
Thanks! Hm. sqlaudit finalize. Does not tell much.
Can you tell if this occured in a special request or does it occur in all requests?

**Comment by jh23453** [comment]
I got the messages while checking the OTP with pam_yubico.
Checking the OTP with privacyidea's webui works without messages.

**Comment by cornelinux** [comment]
Hm, interesting. This error should have occurred with 2.14 also. This does not look new in 2.15.

indeed the validate controller logs the user.login and user.realm
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/validate.py#L231

While the yubico / ttype-controller logs the user Object!
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/ttype.py#L116

**We need to change the ttype controller to also log user.login and user.realm**
