### ISSUE TITLE
'invalid IPNetwork' after adding new proxy client

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#526]
privacyIDEA 2.15, Ubuntu 16.04
Webserver: apache

# What did you try to do?
In the privacyidea config I wanted to add a new proxy (Override Authorization Clients).
The IP addresses should be delimited with ",", but I used a space character.
The configuration has been saved, but a new login ended with
"Authentication failed. invalid IPnetwork ..."

It would be nice to have the configuration checked before saving.
I had to fix the entry in the table config and restart apache to login gain.

Log:
AddrFormatError: invalid IPNetwork 192.168.30.111 fd23:e163:19f7:1234:382d:17e5:2a0e:2f20
[2016-10-18 20:37:00,672][27833][139814537467648][ERROR][privacyidea.app:1423] Exception on /auth [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/auth.py", line 87, in before_request
    get_from_config(SYSCONF.OVERRIDECLIENT))
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/utils.py", line 434, in get_client_ip
    if proxy_settings and check_proxy(client_ip, mapped_ip, proxy_settings):
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/utils.py", line 411, in check_proxy
    proxy_dict = parse_proxy(proxy_settings)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/utils.py", line 388, in parse_proxy
    proxynet = IPNetwork(p_list[0])
  File "/usr/lib/python2.7/dist-packages/netaddr/ip/__init__.py", line 933, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % addr)
AddrFormatError: invalid IPNetwork 192.168.30.111 fd23:e163:19f7:1234:382d:17e5:2a0e:2f20

**Comment by cornelinux** [comment]
This might be a bit difficult to check. As you can also enter:

10.1.1.1, 192.168.0.1 > 10.0.0.0/8

which would allow the IP 192.168.0.1 to rewrite IP addresses to 10.0.0.0/8. The > can also be surrounded by whitespaces. See:

http://privacyidea.readthedocs.io/en/latest/configuration/system_config.html?highlight=proxy#override-authorization-client

So we first would have to strip the whitespaces around ">" and then split bei either "," or " ".

**Comment by cornelinux** [comment]
Saving the config setting is a generic process. At the moment there is no hook or function to check such things. As a compromize we could catch such errors and write en error to the privacyidea.log. 

This way the login would still be possible. However, the ``overrideclient`` would not work, since the parsing failed. The administrator would have to check his log file and fix the setting accordingly.

@jh23453 : Please drop a note, if this would work for you.

**Comment by jh23453** [comment]
Yes, that would work for me.
Thanks
