### ISSUE TITLE
After upgrade "invalid literal for int() with base 10: 'false'"

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#527]
# Versions

privacyIDEA: current trunk
Installation method:
- [x] from source / github
- [ ] in virtualenv
- [x] Debian
- [ ] Ubuntu
- more details:
OS: Debian Jessie
Webserver: NGINX / UWSGI
Database: PostgreSQL

# What did you try to do?
After upgrading the test machine from 16eac1dd996dde486355825d1905bcad099d503a trunk version to current trunk version (and of course upgrading the database model) I tried to access the web ui.

# What outcome did you expect?
The web ui should show the login dialog.

# What outcome did you experience?
PrivacyIDEA presents the following json string, no web ui.
```
{"jsonrpc": "2.0", "signature": "...", "detail": null, "version": "privacyIDEA unknown", "result": {"status": false, "error": {"message": "invalid literal for int() with base 10: 'false'", "code": -500}}, "time": ..., "id": 1}
```

# Log file
```
[2016-10-19 12:37:17,008][23408][140401844664192][ERROR][privacyidea.app:1423] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/local/privacyidea/privacyidea/webui/login.py", line 94, in single_page_application
    password_reset = is_password_reset()
  File "/local/privacyidea/privacyidea/lib/log.py", line 187, in log_wrapper
    f_result = func(*args, **kwds)
  File "/local/privacyidea/privacyidea/lib/passwordreset.py", line 142, in is_password_reset
    rlist = get_resolver_list(editable=True)
  File "/local/privacyidea/privacyidea/lib/log.py", line 187, in log_wrapper
    f_result = func(*args, **kwds)
  File "/local/privacyidea/privacyidea/lib/resolver.py", line 201, in get_resolver_list
    int(reso["data"].get("EDITABLE", 0))
ValueError: invalid literal for int() with base 10: 'false'
[2016-10-19 12:37:17,020][23408][140401844664192][INFO][privacyidea.api.lib.utils:56] We are not able to determine the privacyidea version number.
[2016-10-19 12:37:17,021][23408][140401844664192][DEBUG][privacyidea.api.lib.utils:239] Can not get param: No JSON object could be decoded
```

**Comment by cornelinux** [comment]
Hm. So for some reason the database contains "EDITABLE" = "false". :-/

Quick hack: You can update the database to EDTIABEL="1" in the table resolver_conf.

**Comment by berndnicklas** [comment]
Thanks, Cornelius! Just for documentation, this did the trick:

```
privacyidea=# select * from resolverconfig where "Key"='EDITABLE';
 id  | resolver_id |   Key    | Value | Type | Description 
-----+-------------+----------+-------+------+-------------
 141 |          10 | EDITABLE | false | bool | 
 125 |             | EDITABLE | false | bool | 
 100 |           2 | EDITABLE | false | bool | 
 101 |           3 | EDITABLE | false | bool | 
  99 |           1 | EDITABLE | false | bool | 
 102 |             | EDITABLE | false | bool | 
 107 |             | EDITABLE | false | bool | 
 157 |          11 | EDITABLE | false | bool | 
 173 |          12 | EDITABLE | false | bool | 
 189 |          13 | EDITABLE | false | bool | 
(10 rows)
```

```
privacyidea=# update resolverconfig set "Value"='0' where "Key"='EDITABLE' and "Value"="false";
UPDATE 10
```

```
privacyidea=# select * from resolverconfig where "Key"='EDITABLE';
 id  | resolver_id |   Key    | Value | Type | Description 
-----+-------------+----------+-------+------+-------------
 141 |          10 | EDITABLE | 0     | bool | 
 189 |          13 | EDITABLE | 0     | bool | 
 125 |             | EDITABLE | 0     | bool | 
 100 |           2 | EDITABLE | 0     | bool | 
 101 |           3 | EDITABLE | 0     | bool | 
  99 |           1 | EDITABLE | 0     | bool | 
 102 |             | EDITABLE | 0     | bool | 
 107 |             | EDITABLE | 0     | bool | 
 157 |          11 | EDITABLE | 0     | bool | 
 173 |          12 | EDITABLE | 0     | bool | 
(10 rows)
```

**Comment by cornelinux** [comment]
Thanks a lot for bringing this up!
