### ISSUE TITLE
Problem with IP ranges in policy client IP filter

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#529]
# Versions

privacyIDEA: trunk
Installation method:
- [x] from source / github
- [ ] in virtualenv
- [x] Debian
- [ ] Ubuntu
- more details:
OS: Debian Jessie
Webserver: NGINX / UWSGI

# What did you try to do?
I tried to save an existing policy with existing client IP filter, which contained an IP range.

# What outcome did you expect?

# What outcome did you experience?

Error message:

```
failed to detect a valid IP address from [u'192.168.0.0/16', u'172.16.0.0/12', u'10.0.0.0/8', u'!192.168.1.0/24']
```

# Log file

```
[2016-10-20 14:25:26,792][23742][140001178101632][DEBUG][privacyidea.lib.config:191] Exiting get_from_config with result 192.168.1.100>0.0.0.0/0
[2016-10-20 14:25:26,793][23742][140001178101632][ERROR][privacyidea.app:1423] Exception on /policy/authentication_staff_intranet_clients [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/local/privacyidea/privacyidea/api/auth.py", line 313, in decorated_function
    return f(*args, **kwargs)
  File "/local/privacyidea/privacyidea/api/before_after.py", line 91, in before_admin_request
    before_request()
  File "/local/privacyidea/privacyidea/api/before_after.py", line 118, in before_request
    get_from_config(SYSCONF.OVERRIDECLIENT))
  File "/local/privacyidea/privacyidea/lib/utils.py", line 438, in get_client_ip
    if proxy_settings and check_proxy(client_ip, mapped_ip, proxy_settings):
  File "/local/privacyidea/privacyidea/lib/utils.py", line 414, in check_proxy
    if IPAddress(proxy_ip) in proxynet and IPAddress(rewrite_ip) in \
  File "/usr/lib/python2.7/dist-packages/netaddr/ip/__init__.py", line 307, in __init__
    'address from %r' % addr)
AddrFormatError: failed to detect a valid IP address from [u'192.168.0.0/16', u'172.16.0.0/12', u'10.0.0.0/8', u'!192.168.1.0/24']
[2016-10-20 14:25:26,821][23742][140001178101632][INFO][privacyidea.api.lib.utils:56] We are not able to determine the privacyidea version number.
```

Concrete IP addresses were altered in the published logs. The problem is reproducible by creating a policy containing any IP address range, e.g. 192.168.0.0/16.

**Comment by cornelinux** [comment]
Bad. This worked before. And it is obviously due to the proxyOverRide, since the parameter "client" is used for overriding and for ``GET /audit`` and ``POST /policy``.

You can see this, as the error occures in "get_client_ip" and "check_proxy".

So we simply reduce the proxy checking to this what it is documented for: Authentication.
