### ISSUE TITLE
NoneType object has no attribute 'split' error while viewing user details

### ISSUE THREAD

**Issue by MaRRiK74** [privacyidea/privacyidea#550]
Since last update to version 2.15 we have seen the following notification when viewing user information:

![image](https://cloud.githubusercontent.com/assets/19833001/20482248/f2df4d48-afeb-11e6-874a-2b6b711aec5f.png)

This occurs now and then and only occurred since last update. Closing the browser and logging back on seems to resolve the issue temporary.

**Comment by cornelinux** [comment]
Please take a look into the privacyidea.log.

This might result from event handlers you have configured.

By the way: The current version is 2.16.

**Comment by MaRRiK74** [comment]
We don't have any event handlers configured. Previously the event log didn't show any additional information. Will update to 2.16 this week and see if the issue is resolved.

**Comment by MaRRiK74** [comment]
Just updated my test environment, and the issue is not resolved.
Also this error shows now and then:

![image](https://cloud.githubusercontent.com/assets/19833001/20482828/0ec460ea-afef-11e6-8690-0ce5682995f2.png)

The resolver is present:

![image](https://cloud.githubusercontent.com/assets/19833001/20482844/1fec605c-afef-11e6-894b-a20cb17a4b10.png)

Log file shows:

![image](https://cloud.githubusercontent.com/assets/19833001/20482873/52d04c54-afef-11e6-99ab-666d723faf8b.png)

While clicking around some user details/token details also this new error shows:

![image](https://cloud.githubusercontent.com/assets/19833001/20482906/97377bce-afef-11e6-86b5-8111372a9e21.png)

Logfile:
![image](https://cloud.githubusercontent.com/assets/19833001/20482911/a469c8a6-afef-11e6-9a12-19cc32418510.png)

**Comment by MaRRiK74** [comment]
Concerning the error:
![image](https://cloud.githubusercontent.com/assets/19833001/20482935/c8519fe6-afef-11e6-8e46-68e549dfc141.png)

This is shown in the log:

![image](https://cloud.githubusercontent.com/assets/19833001/20482963/e144b038-afef-11e6-90c5-bbd414acf747.png)

**Comment by cornelinux** [comment]
logfile!

**Comment by MaRRiK74** [comment]
Working on it..

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/auth.py", line 324, in decorated_function
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/before_after.py", line 76, in before_user_request
    before_request()
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/before_after.py", line 120, in before_request
    get_from_config(SYSCONF.OVERRIDECLIENT))
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 187, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/config.py", line 234, in get_from_config
    return_bool=return_bool)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/config.py", line 171, in get_config
    reduced_config[ckey] = self.config[ckey]
KeyError: u'totp.timeStep'

**Comment by MaRRiK74** [comment]
[2016-11-21 13:38:04,819][4848][140433807808256][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:479] Error during fetching LDAP objects: AttributeError("'NoneType' object has no attribute 'items'",)
[2016-11-21 13:38:04,820][4848][140433807808256][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:479] Error during fetching LDAP objects: AttributeError("'NoneType' object has no attribute 'items'",)
[2016-11-21 13:38:04,820][4848][140433807808256][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:479] Error during fetching LDAP objects: AttributeError("'NoneType' object has no attribute 'items'",)
[2016-11-21 13:38:08,707][4848][140433807808256][INFO][privacyidea.lib.user:189] user u'l.de.gier' found in resolver u'SSCZN'
[2016-11-21 13:38:08,707][4848][140433807808256][INFO][privacyidea.lib.user:190] userid resolved to 'eb47bfe3-a557-4eda-92fa-8515b6e4dc61' 
[2016-11-21 13:38:08,853][4848][140433807808256][ERROR][privacyidea.lib.resolver:332] Can not find resolver with name SSCZN 
[2016-11-21 13:38:08,854][4848][140433807808256][INFO][privacyidea.lib.user:184] Resolver u'SSCZN' not found!
[2016-11-21 13:38:08,936][4848][140433757452032][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:479] Error during fetching LDAP objects: AttributeError("'NoneType' object has no attribute 'items'",)
[2016-11-21 13:38:08,936][4848][140433757452032][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:479] Error during fetching LDAP objects: AttributeError("'NoneType' object has no attribute 'items'",)
[2016-11-21 13:38:08,937][4848][140433757452032][ERROR][privacyidea.lib.resolvers.LDAPIdResolver:479] Error during fetching LDAP objects: AttributeError("'NoneType' object has no attribute 'items'",)
[2016-11-21 13:38:08,946][4848][140433807808256][INFO][privacyidea.lib.user:189] user u'l.de.gier' found in resolver u'SSCZN'
[2016-11-21 13:38:08,946][4848][140433807808256][INFO][privacyidea.lib.user:190] userid resolved to 'eb47bfe3-a557-4eda-92fa-8515b6e4dc61' 
[2016-11-21 13:38:09,030][4848][140433807808256][ERROR][privacyidea.app:1423] Exception on /token/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/event.py", line 58, in event_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 187, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/token.py", line 294, in list_api
    user = get_user_from_param(param, optional)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 187, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/user.py", line 549, in get_user_from_param
    user_object = User(login=username, realm=realm)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 187, in log_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/user.py", line 92, in __init__
    self.get_resolvers()
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/user.py", line 186, in get_resolvers
    uid = y.getUserId(self.login)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 123, in cache_wrapper
    f_result = func(self, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 407, in getUserId
    self._bind()
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 311, in _bind
    server_pool = self.get_serverpool(self.uri, self.timeout)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/resolvers/LDAPIdResolver.py", line 615, in get_serverpool
    for uri in urilist.split(","):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by MaRRiK74** [comment]
Log as textfile
[Log.txt](https://github.com/privacyidea/privacyidea/files/603541/Log.txt)

**Comment by MaRRiK74** [comment]
in the logs
user u'username'
resolver u'SSCZN'

The 'u' in front of the items, maybe a typo?

**Comment by cornelinux** [comment]
Is this a pip install?

If so, please run

  pip install ldap3==1.4

**Comment by MaRRiK74** [comment]
No it's not a pip install

**Comment by cornelinux** [comment]
From which planet are you?

**Comment by cornelinux** [comment]
I am no gipsy.

**Comment by cornelinux** [comment]
If you want to use open source, you need to be more active and provide some information.

If you want to play dumb, than you need to get professional help.

This is the rule in any areas of life!

**Comment by MaRRiK74** [comment]
That's one way of 'solving bugs'.. get a good cup of coffee take a deep breath and reread you're comments dude!... Maybe it's time to take a blood pressure lowering pill!

**Comment by MaRRiK74** [comment]
Unless there is an apology don't expect to get anymore input.. I'll wait and see when the bug is resolved in later issues. I'll focus my bughunting and helping with other Open Source projects who DO respect my help!

**Comment by cornelinux** [comment]
Unfortunately I have not seen any help. I had to ask for the log file twice. 
You did not complay to the issue template.
You did not provide ANY information about your installation.
So go and live in your own world!

**Comment by MaRRiK74** [comment]
So tell me how to create log.. evety project has it's own rule to play.. don't be dumb yourself and help others out! and be clear what you want... I have uploaded a log from within /var/log so what else do you need?

**Comment by MaRRiK74** [comment]
I made screenshots of the 'audit log' and I thought you meant that as a log file. Clearly that was not exactly what you were asking for.

**Comment by MaRRiK74** [comment]
If this is what you mean?

**Turn on debug level and take a look at the privacyidea.log!**
**If appropriate, attach the log file.**

You had to ask me for a DEBUGLOG and be specific...  Tomorrow i'll make a debug log, just to please you.

**Comment by cornelinux** [comment]
You may have noticed that there are many ways of installing privacyIDEA. Depending on this you will have different library version, different databases. And this is why I am so tired of guessing anything (which I had to do too often in the past) and why the ISSUE_TEMPLATE was added.

* So how did you install privacyIDEA and
* on which operating system 
* with which database.

**Comment by cornelinux** [comment]
Hm, wait. Are you not ashamed to work on this ticket and expecting me to fix *your* issue *after* calling me an ass?
This is **my** project and it complies to my rules. 
You are free to not like this and you are free to look for any other multi factor authentication system which is thoroughly designed and given to you as present for free. Good luck with that. I guess you will fail on this.
