### ISSUE TITLE
Authentication fails if supplied OTP PIN contains non-ASCII characters

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#753]
I set up one user ``weber`` (LDAP resolver) and assigned a SPASS token with OTP PIN ``haha``. Then, authentication requests fail if the supplied OTP PIN contains non-ASCII characters:

<pre>
$ curl 'http://localhost:5000/validate/check?user=weber&pass=hühü' | json_pp
{
   "time" : 1501755322.07577,
   "result" : {
      "error" : {
         "message" : "'ascii' codec can't encode character u'\\xfc' in position 1: ordinal not in range(128)",
         "code" : -500
      },
      "status" : false
   },
   "version" : "privacyIDEA unknown",
   "signature" : "...",
   "id" : 1,
   "jsonrpc" : "2.0",
   "detail" : null
}
</pre>

The log says:

<pre>
[2017-08-03 12:15:21,963][9094][140501204362304][ERROR][privacyidea.app:1423] Exception on /validate/check [GET]
Traceback (most recent call last):
...
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/tokenclass.py", line 406, in check_pin
    res = self.token.check_pin(pin)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/models.py", line 380, in check_pin
    mypHash = self.get_hashed_pin(pin)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/models.py", line 338, in get_hashed_pin
    self.pin_seed))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
</pre>

**Comment by fredreichbier** [comment]
The relevant line is:
```python
log.debug("hPin: {0!s}, pin: {1!s}, seed: {2!s}".format(binascii.hexlify(hPin),
                                           pin,
                                           self.pin_seed))
```
which fails because ``pin`` is ``unicode`` which gets implicitly converted to ``bytestring`` as long as it only contains ASCII characters. If I replace ``"... pin: {1!s} ..."`` with ``"... pin: {1!r} ..."``, everything is fine and authentication works for both ASCII and non-ASCII PINs.

We could check the code for more occurrences of that pattern (unicode string inserted into bytestring formatstring).
