### ISSUE TITLE
Review format strings in order to fix issues with non-ASCII strings

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#754]
The reason for some issues with non-ASCII characters (#738, #753) seems to be format strings and [implicit string conversion in Python 2](http://washort.twistedmatrix.com/2010/11/unicode-in-python-and-how-to-prevent-it.html). 

I believe some issues were actually introduced in privacyIDEA 2.12 by 6e0ef1d5e, which migrated the codebase from ``%`` string formatting to ``.format`` calls. While this is a good thing in general, it may introduce some regressions. Consider the following example:

```python

>>> "something: %s %s" % ("ascii", u"nön-äscii") # worked, result is unicode
u'something: ascii n\xf6n-\xe4scii'
>>> "something: {!s} {!s}".format("ascii", u"nön-äscii") # breaks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
>>> u"something: {!s} {!s}".format("ascii", u"nön-äscii") # works
u'something: ascii n\xf6n-\xe4scii'
```

So we should look out for bytestring format strings and unicode values.

**Comment by fredreichbier** [comment]
I manually reviewed the changes made in 6e0ef1d and pushed some fixes on [754/unicode-issues](https://github.com/privacyidea/privacyidea/compare/master...754/unicode-issues).
There are some other possible issues, but I haven't checked if they're really a problem yet:
* Setting systemconfig with non-ASCII values (does this happen)?
* ``User.__str__`` fails for non-ASCII usernames
* Does the passwd resolver work with non-ASCII usernames? Not sure if it should.
* Does the SQL resolver work with non-ASCII usernames? Haven't checked yet.
* I *think* the TiQR token may fail for non-ASCII usernames, but I haven't checked.
* I think certificate enrollment via the Web UI fails for non-ASCII usernames.
* Policies with non-ASCII action values may fail.
* CA connectors with non-ASCII names fail, but maybe we should just restrict their names to ASCII.
* Creating/Updating/Deleting users with non-ASCII usernames may fail.

**Comment by fredreichbier** [comment]
#784 fixes some of the aforementioned issues. Remaining issues are:

> Does the passwd resolver work with non-ASCII usernames? Not sure if it should.

Should we put any work into this? I'm not sure non-ASCII usernames are even allowed in ``/etc/passwd``.

> I think certificate enrollment via the Web UI fails for non-ASCII usernames.

I had a closer look and this only seems to be the case for the ``/certificate`` API from ``privacyidea/webui/certificate.py``. I'm not sure if this API is officially supported?

> Policies with non-ASCII action values may fail.

I haven't tested this.

One new issue I found:
Getting the system documentation does not work if resolver, realm or system config values involve non-ASCII values. This is because of the ``.decode('utf-8')`` lines introduced in 7a6fef5f7a5b8f79cf1edc82208905776feeb07f -- they crash if ``k`` or ``v`` are unicode objects with non-ASCII characters. But the commit states that this fixes encoding issues, so I'm not sure what to do :)

**Comment by cornelinux** [comment]
In regards to the passwd resolver:
We might want to support non-ascii usernames, even if these are not supported in /etc/passwd. Acutally it is a file resolver and you could as well create a new file (other than /etc/passwd) and put non-ascii usernames in it.

**Comment by fredreichbier** [comment]
I just noticed a problem with non-ASCII policy attributes:
I created a ``otppin=userstore`` policy and set ``kölbel`` as the user. Authentication of *any* user then fails with:
<pre>
[2017-10-18 15:07:20,717][4542][140613065831616][ERROR][privacyidea.app:1423] Exception on /validate/check [POST]
Traceback (most recent call last):
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/decorators.py", line 91, in check_user_or_serial_in_request_wrapper
    f_result = func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/subscriptions.py", line 316, in check_subscription_wrapper
    f_result = func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/event.py", line 60, in event_wrapper
    f_result = func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/api/validate.py", line 299, in check
    result, details = check_user_pass(user, password, options=options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 196, in auth_cache
    return wrapped_function(user_object, passw, options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 273, in auth_user_does_not_exist
    return wrapped_function(user_object, passw, options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 235, in auth_user_has_no_token
    return wrapped_function(user_object, passw, options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 352, in auth_user_timelimit
    res, reply_dict = wrapped_function(user_object, passw, options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 440, in auth_lastauth
    res, reply_dict = wrapped_function(user_or_serial, passw, options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 329, in auth_user_passthru
    return wrapped_function(user_object, passw, options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/token.py", line 1896, in check_user_pass
    options=options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/token.py", line 1962, in check_token_list
    tokenobject.authenticate(passw, user, options=options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/decorators.py", line 44, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/tokenclass.py", line 445, in authenticate
    pin_match = self.check_pin(pin, user=user, options=options)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policydecorators.py", line 593, in auth_otppin
    client=clientip)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policy.py", line 610, in get_action_values
    client=client)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policy.py", line 501, in get_policies
    policy.get(searchkey), searchvalue)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/lib/policy.py", line 430, in _search_value
    if re.search("^{0!s}$".format(value), searchvalue):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
</pre>

**Comment by cornelinux** [comment]
Ah - why should *kölbel* authenticate, anyway! ;-)

**Comment by fredreichbier** [comment]
Or anyone, for that matter :-)

The remaining issues of this ticket I'll work on are:
* Unicode support for the passwd resolver
* Check whether certificate enrollment via the `/certificate` API is officially supported. If that's the case, we should fix it.
* Check retrieval of the system documentation with non-ASCII values -- especially why the ``.decode`` lines were introduced in 7a6fef5 in the first place.
