### ISSUE TITLE
privacyidea-token-janitor exception on locked token

### ISSUE THREAD

**Issue by kolosovski** [privacyidea/privacyidea#779]
# What did you try to do?

privacyidea-token-janitor find --orphaned 1 --action unassign

# What outcome did you expect?

Unassigning token 324AE64AC5364F
Unassigning token DA5D8980E16410
Unassigning token 03DD4444189A29
Unassigning token 11F71E63E63AFA
...and so on...

# What outcome did you experience?

```
Unassigning token OATH38969372
Traceback (most recent call last):
  File "/usr/bin/privacyidea-token-janitor", line 351, in <module>
    manager.run()
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/bin/privacyidea-token-janitor", line 335, in find
    unassign_token(serial=token_obj.token.serial)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 69, in user_or_serial_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/token.py", line 1110, in unassign_token
    tokenobject.set_pin("")
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 43, in token_locked_wrapper
    "token is locked"), id=1007)
privacyidea.lib.error.TokenAdminError: ERR1007: This action is not possible, since the token is locked
```

# Configuration

* privacyIDEA Version: 2.19.1

* Installation method: from ubuntu packages

## more details: 

* OS: Ubuntu 14.04

* Webserver: apache2

* Tokendatabase: MySQL

Please try to reproduce and fix.
By "Fix" I mean handle exception. If it is no way to unassign locked tokens, the script might either skip and this token and print about this, or maybe additional key should exist to force unassign locked tokens or whatever you think is the best option.

**Comment by cornelinux** [comment]
I think the best way is to catch the exception and print out the info.
If the token is locked, it is locked. The locked state meams, it can not be modified, which also means, it can not be unassigned.

**Comment by kolosovski** [comment]
Correct.
Thank you!
