### ISSUE TITLE
Certificate Token: Generating keys in the browser fails with non-ASCII username

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#812]
Steps to reproduce:

* set up a local CA
* log in to selfservice as a user with non-ASCII username
* enroll a new certificate token
* uncheck "generate keys on the server"
* click "open new tab to create certificate request", fill out the form, click submit

Error in log:
```
[2017-10-25 14:07:48,765][19131][140714023257280][ERROR][privacyidea.app:1423] Exception on /certificate/enroll [POST]
Traceback (most recent call last):
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fred/dev/netknights/privacyidea/privacyidea/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fred/dev/netknights/privacyidea/privacyidea/privacyidea/webui/certificate.py", line 89, in cert_enroll
    email)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
```

The problem is the following format string (see #754):
```python
                           username="{0!s}@{1!s}".format(request.PI_username,
                                               request.PI_realm),
```

**Comment by cornelinux** [comment]
Was it fixed with #813?

**Comment by fredreichbier** [comment]
Nope, this one and #811 are still unfixed.

**Comment by cornelinux** [comment]
The ``username`` in ``render_template`` is only used for displaying it on the web page (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/templates/token_enrolled.html#L23).
So I think it is no problem to convert it accordingly, so that it will not fail.

**Comment by fredreichbier** [comment]
Ah, right, yes, this can be fixed easily. The other problem is that the username is included in the SPKAC CSR:
```python
    csr = """SPKAC={0!s}
CN={1!s},CN={2!s},O={3!s}
emailAddress={4!s}
""".format(request_key,
       request.PI_username,
       request.PI_role,
       request.PI_realm,
       email)
```
Even if we change this to `u"""`, IIRC the `openssl` invocation fails because we have to tell openssl that the CSR contains UTF-8 data explicitly.

**Comment by cornelinux** [comment]
Ah-jetzt-ja.
https://stackoverflow.com/questions/16478452/how-to-create-csr-with-utf8-subject-in-openssl

We need to use the parameter "-utf", which is not in my manpage... :-/
