### ISSUE TITLE
U2F fails on authentication step

### ISSUE THREAD

**Issue by Harry97** [privacyidea/privacyidea#961]
# What did you try to do?
Add a second authentication step (U2F) for SimpleSAMLphp 

# What outcome did you expect?
After successfully entering the user userstore password, he should be asked to provide the U2F token signature by pressing it, and if this token truly belongs to him, he should be passed on.

# What did acutally happen?

After entering the password, the U2F screen appears for a second then I'm given `Bad request received`
`There is an error in the request to this page. The reason was: Valid JSON response, but some internal error occured in privacyidea server.`

# Configuration

* privacyIDEA Version:
  
Package: privacyidea-apache2
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 81
Maintainer: Cornelius Kölbel <cornelius@privacyidea.org>
Architecture: all
Source: python-privacyidea
Version: 2.21.4-1xenial
Depends: python-privacyidea, python-mysqldb, apache2, mysql-server | mariadb-server, mysql-client | mariadb-client, libapache2-mod-wsgi, rng-tools
Conflicts: nginx, nginx-full, privacyidea-nginx
Conffiles:
 /etc/apache2/sites-available/privacyidea.conf 91e94c20b6e10e1ae50efa63a10fab75
 /etc/privacyidea/CA/openssl.cnf 4be876c63b7f7f4050ee930c48850e95
 /etc/privacyidea/NetKnights.pem 0a3222fbc4ec2224e6cd96214d7e9de5
 /etc/privacyidea/dictionary b4760f536a60b98b850843e0350a35af
 /etc/privacyidea/pi.cfg 6c0be32941d44d9bf54b160aac8260d0
 /etc/privacyidea/privacyideaapp.wsgi 91902c84c48015c9f6656897426df31b
Description: 2FA system. This is a meta package to install privacyidea with apache2
 privacyIDEA: identity, multifactor authentication, authorization.
 This is the package that installs all requirements to run privacyIDEA in the
 Apache2 Webserver.

* Installation method:
  From ubuntu packages

# Log file
```
[2018-03-05 12:26:42,769][24702][140676673824512][WARNING][privacyidea.lib.utils:583] Proxy 159.65.239.49 not allowed to set IP to 197.246.8.25.
[2018-03-05 12:26:42,785][24702][140676673824512][INFO][privacyidea.lib.user:230] user u'maher' found in resolver u'test'
[2018-03-05 12:26:42,785][24702][140676673824512][INFO][privacyidea.lib.user:231] userid resolved to 2 
[2018-03-05 12:26:42,836][24702][140676673824512][ERROR][privacyidea.app:1423] Exception on /validate/samlcheck [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 91, in check_user_or_serial_in_request_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/subscriptions.py", line 331, in check_subscription_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 117, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/event.py", line 60, in event_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/validate.py", line 378, in samlcheck
    auth, details = check_user_pass(user, password, options=options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 196, in auth_cache
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 273, in auth_user_does_not_exist
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 235, in auth_user_has_no_token
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 352, in auth_user_timelimit
    res, reply_dict = wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 440, in auth_lastauth
    res, reply_dict = wrapped_function(user_or_serial, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 329, in auth_user_passthru
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/token.py", line 1898, in check_user_pass
    options=options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/token.py", line 2080, in check_token_list
    options=options) >= 0:
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 44, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/tokenclass.py", line 1424, in check_challenge_response
    otp_counter = self.check_otp(passw, options=options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 44, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/tokens/u2ftoken.py", line 449, in check_otp
    clientdata = url_decode(clientdata)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/tokens/u2f.py", line 46, in url_decode
    res = base64.urlsafe_b64decode(str(url) + padding)
  File "/usr/lib/python2.7/base64.py", line 119, in urlsafe_b64decode
    return b64decode(s.translate(_urlsafe_decode_translation))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```
It's also worth noting that while registering the token for the user, an error poped up telling me that the attestation time was invalid, but the token was attached to the user. Also, to cement that this occurs on the U2F step, I tried to authenticate on Mozila where U2Fs aren't supported yet, and U2F steps page didn't return any error.

SimpleSAMLphp privacyIdea configuration: 
```
  'example-privacyidea' => array(
        'privacyidea:privacyidea',
        'privacyideaserver' => 'https://pi.is.com',
        'sslverifyhost' => False,
        'sslverifypeer' => False,
        //'otpextra' => 1,
        'attributemap' => array('username' => 'samlLoginName',
                                 'surname' => 'surName',
                                 'givenname' => 'givenName',
                                 'email' => 'emailAddress',
                                 'phone' => 'telePhone',
                                 'mobile' => 'mobilePhone'),
),
```

**Comment by cornelinux** [comment]
If an error occurs during registration the token is NOT enrolled correctly!
The token object however is created, but the assymmetric keys are not generated!

PrivacyIDEA does not allow to use non-valid attestation certs.
This can only be configued in version 2.22.
See https://github.com/privacyidea/privacyidea/issues/926

**Comment by Harry97** [comment]
Thanks for replying.

Well, why would it carry on and create a token object where it's very likely for an error to happen?! Anyway, I'mma install 2.22 version and try again, hopefully this will fix the problem.

**Comment by cornelinux** [comment]
> Well, why would it carry on and create a token object where it's very likely to cause an error later on?! Anyway, I'mma try to upgrade to 2.22 and try again, hopefully this will fix the problem.

Actually it is not very likely, that the enrollment will fail ;-)
Anyway, from an internal workflow perspective it is necessary, that the token exists as an object, so that a key pair can be generated. The token could however be deleted if the authentication has failed.

**Comment by Harry97** [comment]
I add an enrollment policy where attestation time was check field was marked and the token got registered successfully, yet when I tried to login using simpleSAMLPHP, this is error happened: 
```
Exception on /validate/samlcheck [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/postpolicy.py", line 102, in policy_wrapper
    response = wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 120, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 120, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 120, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 91, in check_user_or_serial_in_request_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/subscriptions.py", line 331, in check_subscription_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/lib/prepolicy.py", line 120, in policy_wrapper
    return wrapped_function(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/event.py", line 60, in event_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/api/validate.py", line 428, in samlcheck
    auth, details = check_user_pass(user, password, options=options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 196, in auth_cache
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 273, in auth_user_does_not_exist
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 235, in auth_user_has_no_token
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 352, in auth_user_timelimit
    res, reply_dict = wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 440, in auth_lastauth
    res, reply_dict = wrapped_function(user_or_serial, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/policydecorators.py", line 329, in auth_user_passthru
    return wrapped_function(user_object, passw, options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/token.py", line 1947, in check_user_pass
    options=options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/token.py", line 2129, in check_token_list
    options=options) >= 0:
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 44, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/tokenclass.py", line 1434, in check_challenge_response
    otp_counter = self.check_otp(passw, options=options)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/decorators.py", line 44, in token_locked_wrapper
    f_result = func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/tokens/u2ftoken.py", line 461, in check_otp
    clientdata = url_decode(clientdata)
  File "/usr/lib/python2.7/dist-packages/privacyidea/lib/tokens/u2f.py", line 46, in url_decode
    res = base64.urlsafe_b64decode(str(url) + padding)
  File "/usr/lib/python2.7/base64.py", line 119, in urlsafe_b64decode
    return b64decode(s.translate(_urlsafe_decode_translation))
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    except binascii.Error, msg:
NameError: global name 'msg' is not defined
```

**Comment by cornelinux** [comment]
You updated to 2.22?

This is interesting. We can not do anything against this error, since it occurs in ``base64`` of the python stdlib. Well, somehow your padding seems to be wrong.   And my assumption is, that the padding actually stems from the u2f device.

Did you try to authenticate at the privacyIDEA webui using u2f?

Which device are you using?

(And yes, I did not have problems with yubikeys, yet)

**Comment by Harry97** [comment]
I apologize, as I know this'd come off as stupid but how do I enable U2F step for the webui?
I followed this [video](https://www.youtube.com/watch?v=qcQlENAyxgQ), adding a token to a user and then creating a webui policy that forces the users to authenticate against privacyIDEA, but everytime I try to login I get "Authentication Failed".

I'm using a regular u2fzero device, nothing special about it.
Here's the technical data, if it could be of any help to us:
```
Registration Data
origin: https://demo.yubico.com
version: U2F_V2
challenge: kI9l-g69nhbhYDTgHDeKjxgFX1yU8jWWBYYPQvgyvbY
appId: https://demo.yubico.com

Response Data
clientData: {"typ":"navigator.id.finishEnrollment","challenge":"kI9l-g69nhbhYDTgHDeKjxgFX1yU8jWWBYYPQvgyvbY","origin":"https://demo.yubico.com","cid_pubkey":"unused"}
registrationData: 0504d42455473de164bfb54806aed56d7ff6785e1e5b92e3c4e3d3b3d7bb442c1c445ad25b3fd2de551643b374a17be1f9a00a367e140a93cb10ff3505310d2e4f5d24c13e99dfddaf9393336795778e51f50363f518292573a7eecfe96068f3ee842c3a12bd81308201de30820185020100300a06082a8648ce3d040302307b310b3009060355040613025553310b300906035504080c0256413113301106035504070c0a426c61636b73627572673110300e060355040a0c07436f6e6f72436f3114301206035504030c0b636f6e6f72636f2e636f6d3122302006092a864886f70d0109011613636f6e6f72636f40636f6e6f72636f2e636f6d301e170d3137303230323232303432345a170d3137303330343232303432345a307c310b3009060355040613025553310b300906035504080c0256413113301106035504070c0a426c61636b73627572673111300f060355040a0c08553246205a65726f3114301206035504030c0b7532667a65726f2e636f6d3122302006092a864886f70d0109011613636f6e6f72636f40636f6e6f72636f2e636f6d3059301306072a8648ce3d020106082a8648ce3d03010703420004a1155e6372c345ec97c12ac2ba84f863f1ae6ff17d800402a19f8606e422a7c02be4e34461153efbd41324ec84b254ec5852910d55b19b3079f588dbf305839a300a06082a8648ce3d04030203470030440220205c9e1d0d57cc2f0b25f0971cbf398ea3b20f9c9771fbfe88f4f9a103134cb6022026eedaaed8bf7c93700fcd1a264c52fae386293350b17a21112c03398dfde256304502203bb8a76ac6ec9842009836469dcec4e42899bad152f996d8eae62e89fde23c40022100e3b07cf7bd1695f40858655afeda9f2dabfa325f848bd228be0a2398d6ebee2c

Attestation Certificate
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 0 (0x0)
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=US, ST=VA, L=Blacksburg, O=ConorCo, CN=conorco.com/emailAddress=conorco@conorco.com
        Validity
            Not Before: Feb  2 22:04:24 2017 GMT
            Not After : Mar  4 22:04:24 2017 GMT
        Subject: C=US, ST=VA, L=Blacksburg, O=U2F Zero, CN=u2fzero.com/emailAddress=conorco@conorco.com
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:a1:15:5e:63:72:c3:45:ec:97:c1:2a:c2:ba:84:
                    f8:63:f1:ae:6f:f1:7d:80:04:02:a1:9f:86:06:e4:
                    22:a7:c0:2b:e4:e3:44:61:15:3e:fb:d4:13:24:ec:
                    84:b2:54:ec:58:52:91:0d:55:b1:9b:30:79:f5:88:
                    db:f3:05:83:9a
                ASN1 OID: prime256v1
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:20:5c:9e:1d:0d:57:cc:2f:0b:25:f0:97:1c:bf:
         39:8e:a3:b2:0f:9c:97:71:fb:fe:88:f4:f9:a1:03:13:4c:b6:
         02:20:26:ee:da:ae:d8:bf:7c:93:70:0f:cd:1a:26:4c:52:fa:
         e3:86:29:33:50:b1:7a:21:11:2c:03:39:8d:fd:e2:56
-----BEGIN CERTIFICATE-----
MIIB3jCCAYUCAQAwCgYIKoZIzj0EAwIwezELMAkGA1UEBhMCVVMxCzAJBgNVBAgM
AlZBMRMwEQYDVQQHDApCbGFja3NidXJnMRAwDgYDVQQKDAdDb25vckNvMRQwEgYD
VQQDDAtjb25vcmNvLmNvbTEiMCAGCSqGSIb3DQEJARYTY29ub3Jjb0Bjb25vcmNv
LmNvbTAeFw0xNzAyMDIyMjA0MjRaFw0xNzAzMDQyMjA0MjRaMHwxCzAJBgNVBAYT
AlVTMQswCQYDVQQIDAJWQTETMBEGA1UEBwwKQmxhY2tzYnVyZzERMA8GA1UECgwI
VTJGIFplcm8xFDASBgNVBAMMC3UyZnplcm8uY29tMSIwIAYJKoZIhvcNAQkBFhNj
b25vcmNvQGNvbm9yY28uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoRVe
Y3LDReyXwSrCuoT4Y/Gub/F9gAQCoZ+GBuQip8Ar5ONEYRU++9QTJOyEslTsWFKR
DVWxmzB59Yjb8wWDmjAKBggqhkjOPQQDAgNHADBEAiAgXJ4dDVfMLwsl8JccvzmO
o7IPnJdx+/6I9PmhAxNMtgIgJu7arti/fJNwD80aJkxS+uOGKTNQsXohESwDOY39
4lY=
-----END CERTIFICATE-----
```
